// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: pkg/capture/agent/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentIngest_Push_FullMethodName = "/gta.agent.AgentIngest/Push"
)

// AgentIngestClient is the client API for AgentIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentIngest 由 gta-pipeline 的 agent capture source 侧提供（gRPC server，默认 :9092）。
// 团队成员本机的 gta-agent 抓取本机流量后作为 client 连接并推送原始完整帧。
//
// 与 mobile source 不同：这里保留完整帧（raw）与链路层类型（link_type），
// 插件在本地开发与在团队服务端跑的行为完全一致（不做 LinkTypeProxyPayload 退化）。
type AgentIngestClient interface {
	// Push 客户端流式推送 PacketBatch；流结束返回汇总统计。
	// agent 重连期间的包允许丢失（服务端按无订阅者/慢消费者计数丢弃，不缓存补发）。
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PacketBatch, PushAck], error)
}

type agentIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentIngestClient(cc grpc.ClientConnInterface) AgentIngestClient {
	return &agentIngestClient{cc}
}

func (c *agentIngestClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PacketBatch, PushAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngest_ServiceDesc.Streams[0], AgentIngest_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PacketBatch, PushAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_PushClient = grpc.ClientStreamingClient[PacketBatch, PushAck]

// AgentIngestServer is the server API for AgentIngest service.
// All implementations must embed UnimplementedAgentIngestServer
// for forward compatibility.
//
// AgentIngest 由 gta-pipeline 的 agent capture source 侧提供（gRPC server，默认 :9092）。
// 团队成员本机的 gta-agent 抓取本机流量后作为 client 连接并推送原始完整帧。
//
// 与 mobile source 不同：这里保留完整帧（raw）与链路层类型（link_type），
// 插件在本地开发与在团队服务端跑的行为完全一致（不做 LinkTypeProxyPayload 退化）。
type AgentIngestServer interface {
	// Push 客户端流式推送 PacketBatch；流结束返回汇总统计。
	// agent 重连期间的包允许丢失（服务端按无订阅者/慢消费者计数丢弃，不缓存补发）。
	Push(grpc.ClientStreamingServer[PacketBatch, PushAck]) error
	mustEmbedUnimplementedAgentIngestServer()
}

// UnimplementedAgentIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentIngestServer struct{}

func (UnimplementedAgentIngestServer) Push(grpc.ClientStreamingServer[PacketBatch, PushAck]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedAgentIngestServer) mustEmbedUnimplementedAgentIngestServer() {}
func (UnimplementedAgentIngestServer) testEmbeddedByValue()                     {}

// UnsafeAgentIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentIngestServer will
// result in compilation errors.
type UnsafeAgentIngestServer interface {
	mustEmbedUnimplementedAgentIngestServer()
}

func RegisterAgentIngestServer(s grpc.ServiceRegistrar, srv AgentIngestServer) {
	// If the following call panics, it indicates UnimplementedAgentIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentIngest_ServiceDesc, srv)
}

func _AgentIngest_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentIngestServer).Push(&grpc.GenericServerStream[PacketBatch, PushAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_PushServer = grpc.ClientStreamingServer[PacketBatch, PushAck]

// AgentIngest_ServiceDesc is the grpc.ServiceDesc for AgentIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gta.agent.AgentIngest",
	HandlerType: (*AgentIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _AgentIngest_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/capture/agent/proto/agent.proto",
}
