// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: pkg/capture/agent/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentIngest_Push_FullMethodName = "/gta.agent.AgentIngest/Push"
)

// AgentIngestClient is the client API for AgentIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentIngest 由 gta-pipeline 的 agent capture source 侧提供（gRPC server，默认 :9092）。
// 团队成员本机的 gta-agent 抓取本机流量后作为 client 连接并推送原始完整帧。
//
// 与 mobile source 不同：这里保留完整帧（raw）与链路层类型（link_type），
// 插件在本地开发与在团队服务端跑的行为完全一致（不做 LinkTypeProxyPayload 退化）。
type AgentIngestClient interface {
	// Push 客户端流式推送 PacketBatch；流结束返回汇总统计。
	// agent 重连期间的包允许丢失（服务端按无订阅者/慢消费者计数丢弃，不缓存补发）。
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PacketBatch, PushAck], error)
}

type agentIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentIngestClient(cc grpc.ClientConnInterface) AgentIngestClient {
	return &agentIngestClient{cc}
}

func (c *agentIngestClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PacketBatch, PushAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngest_ServiceDesc.Streams[0], AgentIngest_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PacketBatch, PushAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_PushClient = grpc.ClientStreamingClient[PacketBatch, PushAck]

// AgentIngestServer is the server API for AgentIngest service.
// All implementations must embed UnimplementedAgentIngestServer
// for forward compatibility.
//
// AgentIngest 由 gta-pipeline 的 agent capture source 侧提供（gRPC server，默认 :9092）。
// 团队成员本机的 gta-agent 抓取本机流量后作为 client 连接并推送原始完整帧。
//
// 与 mobile source 不同：这里保留完整帧（raw）与链路层类型（link_type），
// 插件在本地开发与在团队服务端跑的行为完全一致（不做 LinkTypeProxyPayload 退化）。
type AgentIngestServer interface {
	// Push 客户端流式推送 PacketBatch；流结束返回汇总统计。
	// agent 重连期间的包允许丢失（服务端按无订阅者/慢消费者计数丢弃，不缓存补发）。
	Push(grpc.ClientStreamingServer[PacketBatch, PushAck]) error
	mustEmbedUnimplementedAgentIngestServer()
}

// UnimplementedAgentIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentIngestServer struct{}

func (UnimplementedAgentIngestServer) Push(grpc.ClientStreamingServer[PacketBatch, PushAck]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedAgentIngestServer) mustEmbedUnimplementedAgentIngestServer() {}
func (UnimplementedAgentIngestServer) testEmbeddedByValue()                     {}

// UnsafeAgentIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentIngestServer will
// result in compilation errors.
type UnsafeAgentIngestServer interface {
	mustEmbedUnimplementedAgentIngestServer()
}

func RegisterAgentIngestServer(s grpc.ServiceRegistrar, srv AgentIngestServer) {
	// If the following call panics, it indicates UnimplementedAgentIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentIngest_ServiceDesc, srv)
}

func _AgentIngest_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentIngestServer).Push(&grpc.GenericServerStream[PacketBatch, PushAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_PushServer = grpc.ClientStreamingServer[PacketBatch, PushAck]

// AgentIngest_ServiceDesc is the grpc.ServiceDesc for AgentIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gta.agent.AgentIngest",
	HandlerType: (*AgentIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _AgentIngest_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/capture/agent/proto/agent.proto",
}

const (
	AgentControl_RegisterProbe_FullMethodName = "/gta.agent.AgentControl/RegisterProbe"
	AgentControl_Connect_FullMethodName       = "/gta.agent.AgentControl/Connect"
	AgentControl_UploadArchive_FullMethodName = "/gta.agent.AgentControl/UploadArchive"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlClient interface {
	// RegisterProbe 注册探针并换发长期凭证。鉴权：用户 token（claim 所得）。
	// 同一机器重复注册（token 丢失重接）携带 prev_probe_id 覆盖旧记录。
	RegisterProbe(ctx context.Context, in *RegisterProbeRequest, opts ...grpc.CallOption) (*RegisterProbeAck, error)
	// Connect 控制双向流。鉴权：probe_token。开流首包必须是 ProbeHello。
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlEvent, Command], error)
	// UploadArchive 归档回放上传。鉴权：probe_token。
	UploadArchive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArchiveChunk, UploadArchiveAck], error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) RegisterProbe(ctx context.Context, in *RegisterProbeRequest, opts ...grpc.CallOption) (*RegisterProbeAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterProbeAck)
	err := c.cc.Invoke(ctx, AgentControl_RegisterProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlEvent, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlEvent, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_ConnectClient = grpc.BidiStreamingClient[ControlEvent, Command]

func (c *agentControlClient) UploadArchive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArchiveChunk, UploadArchiveAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[1], AgentControl_UploadArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArchiveChunk, UploadArchiveAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_UploadArchiveClient = grpc.ClientStreamingClient[ArchiveChunk, UploadArchiveAck]

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
type AgentControlServer interface {
	// RegisterProbe 注册探针并换发长期凭证。鉴权：用户 token（claim 所得）。
	// 同一机器重复注册（token 丢失重接）携带 prev_probe_id 覆盖旧记录。
	RegisterProbe(context.Context, *RegisterProbeRequest) (*RegisterProbeAck, error)
	// Connect 控制双向流。鉴权：probe_token。开流首包必须是 ProbeHello。
	Connect(grpc.BidiStreamingServer[ControlEvent, Command]) error
	// UploadArchive 归档回放上传。鉴权：probe_token。
	UploadArchive(grpc.ClientStreamingServer[ArchiveChunk, UploadArchiveAck]) error
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) RegisterProbe(context.Context, *RegisterProbeRequest) (*RegisterProbeAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterProbe not implemented")
}
func (UnimplementedAgentControlServer) Connect(grpc.BidiStreamingServer[ControlEvent, Command]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentControlServer) UploadArchive(grpc.ClientStreamingServer[ArchiveChunk, UploadArchiveAck]) error {
	return status.Error(codes.Unimplemented, "method UploadArchive not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_RegisterProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).RegisterProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_RegisterProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).RegisterProbe(ctx, req.(*RegisterProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServer).Connect(&grpc.GenericServerStream[ControlEvent, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_ConnectServer = grpc.BidiStreamingServer[ControlEvent, Command]

func _AgentControl_UploadArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServer).UploadArchive(&grpc.GenericServerStream[ArchiveChunk, UploadArchiveAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_UploadArchiveServer = grpc.ClientStreamingServer[ArchiveChunk, UploadArchiveAck]

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gta.agent.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProbe",
			Handler:    _AgentControl_RegisterProbe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentControl_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadArchive",
			Handler:       _AgentControl_UploadArchive_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/capture/agent/proto/agent.proto",
}
