// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: pkg/capture/agent/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PacketBatch 是一批来自同一会话同一网卡的原始包。
type PacketBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 目标抓包会话
	Iface         string                 `protobuf:"bytes,2,opt,name=iface,proto3" json:"iface,omitempty"`                          // agent 侧抓包网卡名（仅记录用）
	Packets       []*RawPacket           `protobuf:"bytes,3,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketBatch) Reset() {
	*x = PacketBatch{}
	mi := &file_pkg_capture_agent_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketBatch) ProtoMessage() {}

func (x *PacketBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_agent_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketBatch.ProtoReflect.Descriptor instead.
func (*PacketBatch) Descriptor() ([]byte, []int) {
	return file_pkg_capture_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PacketBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketBatch) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *PacketBatch) GetPackets() []*RawPacket {
	if x != nil {
		return x.Packets
	}
	return nil
}

// RawPacket 是一个完整原始帧（含链路层头），与 pcap 抓到的帧等价。
type RawPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                       // agent 侧生成（UUIDv7）；为空时 pipeline 会补 ID
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Unix 纳秒时间戳；0 表示使用服务端接收时刻
	LinkType      uint32                 `protobuf:"varint,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`          // gopacket layers.LinkType 数值，原样保留
	Raw           []byte                 `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`                                     // 完整原始帧
	Src           string                 `protobuf:"bytes,5,opt,name=src,proto3" json:"src,omitempty"`                                     // "ip:port"（可选，pipeline 解析失败不阻塞）
	Dst           string                 `protobuf:"bytes,6,opt,name=dst,proto3" json:"dst,omitempty"`
	Protocol      string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`                                                                           // 如 "tcp"；为空由解码器自行判断
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 附加元数据（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPacket) Reset() {
	*x = RawPacket{}
	mi := &file_pkg_capture_agent_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacket) ProtoMessage() {}

func (x *RawPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_agent_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacket.ProtoReflect.Descriptor instead.
func (*RawPacket) Descriptor() ([]byte, []int) {
	return file_pkg_capture_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RawPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RawPacket) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *RawPacket) GetLinkType() uint32 {
	if x != nil {
		return x.LinkType
	}
	return 0
}

func (x *RawPacket) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *RawPacket) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RawPacket) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RawPacket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RawPacket) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PushAck 是流结束时的汇总统计。
type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       uint64                 `protobuf:"varint,1,opt,name=batches,proto3" json:"batches,omitempty"`     // 已接收 batch 数
	Packets       uint64                 `protobuf:"varint,2,opt,name=packets,proto3" json:"packets,omitempty"`     // 已接收包数
	Delivered     uint64                 `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"` // 成功投递给 capture pipeline 的包数
	Dropped       uint64                 `protobuf:"varint,4,opt,name=dropped,proto3" json:"dropped,omitempty"`     // 因无订阅者或慢消费者丢弃的包数
	Rejected      uint64                 `protobuf:"varint,5,opt,name=rejected,proto3" json:"rejected,omitempty"`   // 因会话归属校验拒绝的 batch 数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_pkg_capture_agent_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_agent_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_pkg_capture_agent_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PushAck) GetBatches() uint64 {
	if x != nil {
		return x.Batches
	}
	return 0
}

func (x *PushAck) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *PushAck) GetDelivered() uint64 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *PushAck) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *PushAck) GetRejected() uint64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

var File_pkg_capture_agent_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_capture_agent_proto_agent_proto_rawDesc = "" +
	"\n" +
	"#pkg/capture/agent/proto/agent.proto\x12\tgta.agent\"r\n" +
	"\vPacketBatch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05iface\x18\x02 \x01(\tR\x05iface\x12.\n" +
	"\apackets\x18\x03 \x03(\v2\x14.gta.agent.RawPacketR\apackets\"\xaa\x02\n" +
	"\tRawPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x1b\n" +
	"\tlink_type\x18\x03 \x01(\rR\blinkType\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\fR\x03raw\x12\x10\n" +
	"\x03src\x18\x05 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x06 \x01(\tR\x03dst\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12>\n" +
	"\bmetadata\x18\b \x03(\v2\".gta.agent.RawPacket.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\aPushAck\x12\x18\n" +
	"\abatches\x18\x01 \x01(\x04R\abatches\x12\x18\n" +
	"\apackets\x18\x02 \x01(\x04R\apackets\x12\x1c\n" +
	"\tdelivered\x18\x03 \x01(\x04R\tdelivered\x12\x18\n" +
	"\adropped\x18\x04 \x01(\x04R\adropped\x12\x1a\n" +
	"\brejected\x18\x05 \x01(\x04R\brejected2C\n" +
	"\vAgentIngest\x124\n" +
	"\x04Push\x12\x16.gta.agent.PacketBatch\x1a\x12.gta.agent.PushAck(\x01B\x1dZ\x1bgta/pkg/capture/agent/protob\x06proto3"

var (
	file_pkg_capture_agent_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_capture_agent_proto_agent_proto_rawDescData []byte
)

func file_pkg_capture_agent_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_capture_agent_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_capture_agent_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_capture_agent_proto_agent_proto_rawDesc), len(file_pkg_capture_agent_proto_agent_proto_rawDesc)))
	})
	return file_pkg_capture_agent_proto_agent_proto_rawDescData
}

var file_pkg_capture_agent_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_capture_agent_proto_agent_proto_goTypes = []any{
	(*PacketBatch)(nil), // 0: gta.agent.PacketBatch
	(*RawPacket)(nil),   // 1: gta.agent.RawPacket
	(*PushAck)(nil),     // 2: gta.agent.PushAck
	nil,                 // 3: gta.agent.RawPacket.MetadataEntry
}
var file_pkg_capture_agent_proto_agent_proto_depIdxs = []int32{
	1, // 0: gta.agent.PacketBatch.packets:type_name -> gta.agent.RawPacket
	3, // 1: gta.agent.RawPacket.metadata:type_name -> gta.agent.RawPacket.MetadataEntry
	0, // 2: gta.agent.AgentIngest.Push:input_type -> gta.agent.PacketBatch
	2, // 3: gta.agent.AgentIngest.Push:output_type -> gta.agent.PushAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_capture_agent_proto_agent_proto_init() }
func file_pkg_capture_agent_proto_agent_proto_init() {
	if File_pkg_capture_agent_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_capture_agent_proto_agent_proto_rawDesc), len(file_pkg_capture_agent_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_capture_agent_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_capture_agent_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_capture_agent_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_capture_agent_proto_agent_proto = out.File
	file_pkg_capture_agent_proto_agent_proto_goTypes = nil
	file_pkg_capture_agent_proto_agent_proto_depIdxs = nil
}
