// Command gen_tool_table 从 cmd/gt-mcp/main.go 的 AddTool/mcp.NewTool 调用
// 重新生成 README.md 中的 MCP 工具目录，防止工具表与代码漂移。
//
// 用法：go run ./scripts/gen_tool_table
// 它替换 README.md 中以下标记之间的内容（含工具数小节标题与表格）：
//
//	<!-- BEGIN TOOL TABLE (generated by scripts/gen_tool_table; do not edit) -->
//	<!-- END TOOL TABLE -->
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

const (
	mainGo = "cmd/gt-mcp/main.go"
	readme = "README.md"

	beginMarker = "<!-- BEGIN TOOL TABLE (generated by scripts/gen_tool_table; do not edit) -->"
	endMarker   = "<!-- END TOOL TABLE -->"
)

type tool struct {
	name string
	desc string
}

func main() {
	tools, err := extractTools(mainGo)
	if err != nil {
		fail(err)
	}
	if len(tools) == 0 {
		fail(fmt.Errorf("no mcp.NewTool calls found in %s", mainGo))
	}

	readmeBytes, err := os.ReadFile(readme)
	if err != nil {
		fail(err)
	}
	old := string(readmeBytes)
	begin := strings.Index(old, beginMarker)
	end := strings.Index(old, endMarker)
	if begin < 0 || end < 0 || end < begin {
		fail(fmt.Errorf("README.md missing %s / %s markers", beginMarker, endMarker))
	}

	out := old[:begin] + genSection(tools) + "\n" + old[end:]
	if err := os.WriteFile(readme, []byte(out), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("README.md tool table regenerated: %d tools\n", len(tools))
}

// extractTools 用 AST 定位每个 mcp.NewTool("name", ...) 调用，取第一个
// mcp.WithDescription("...") 字符串参数作为描述。
func extractTools(path string) ([]tool, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	var tools []tool
	ast.Inspect(f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "NewTool" {
			return true
		}
		if id, ok := sel.X.(*ast.Ident); !ok || id.Name != "mcp" {
			return true
		}
		if len(call.Args) == 0 {
			return true
		}
		name, ok := call.Args[0].(*ast.BasicLit)
		if !ok || name.Kind != token.STRING {
			return true
		}
		t := tool{name: unquote(name.Value)}
		for _, arg := range call.Args[1:] {
			if c, ok := arg.(*ast.CallExpr); ok {
				if s, ok := c.Fun.(*ast.SelectorExpr); ok && s.Sel.Name == "WithDescription" && len(c.Args) > 0 {
					if lit, ok := c.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
						t.desc = firstSentence(unquote(lit.Value))
					}
				}
			}
		}
		tools = append(tools, t)
		return true
	})
	return tools, nil
}

func genSection(tools []tool) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "%s\n", beginMarker)
	fmt.Fprintf(&b, "### MCP tools (%d; `list_raw_packets` / `decode_raw_packets` require `-enable-raw-debug` and are not registered by default)\n", len(tools))
	fmt.Fprintf(&b, "\nGenerated by `go run ./scripts/gen_tool_table` from `cmd/gt-mcp/main.go` — do not edit by hand.\n\n")
	fmt.Fprintf(&b, "| Tool | Purpose (first sentence of description) |\n|------|------|\n")
	for _, t := range tools {
		fmt.Fprintf(&b, "| `%s` | %s |\n", t.name, t.desc)
	}
	return b.String()
}

// firstSentence 截取描述的第一句，保持表格可读；空描述回填占位符。
func firstSentence(s string) string {
	s = strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	if s == "" {
		return "(no description)"
	}
	if i := strings.IndexAny(s, "。"); i > 0 {
		s = s[:i]
	}
	if i := strings.Index(s, ". "); i > 0 {
		s = s[:i]
	}
	s = strings.TrimRight(s, ".。")
	s = strings.ReplaceAll(s, "|", "\\|")
	if r := []rune(s); len(r) > 110 {
		s = strings.TrimSpace(string(r[:110])) + "…"
	}
	return s
}

func unquote(lit string) string {
	s := lit
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		s = s[1 : len(s)-1]
	}
	// 反引号原文与转义都按字面处理；描述里不含需要精确还原的转义序列。
	if !strings.ContainsAny(s, "\\") {
		return s
	}
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] == '\\' && i+1 < len(s) {
			i++
			switch s[i] {
			case 'n':
				b.WriteByte('\n')
			case 't':
				b.WriteByte('\t')
			default:
				b.WriteByte(s[i])
			}
			continue
		}
		b.WriteByte(s[i])
	}
	return b.String()
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gen_tool_table: %v\n", err)
	os.Exit(1)
}
