// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: pkg/plugindev/proto/plugindev.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginDev_Scaffold_FullMethodName    = "/gta.plugindev.PluginDev/Scaffold"
	PluginDev_ListPlugins_FullMethodName = "/gta.plugindev.PluginDev/ListPlugins"
	PluginDev_Build_FullMethodName       = "/gta.plugindev.PluginDev/Build"
	PluginDev_Activate_FullMethodName    = "/gta.plugindev.PluginDev/Activate"
	PluginDev_Deactivate_FullMethodName  = "/gta.plugindev.PluginDev/Deactivate"
	PluginDev_Status_FullMethodName      = "/gta.plugindev.PluginDev/Status"
)

// PluginDevClient is the client API for PluginDev service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginDev is the Developer Plane control surface. It owns the filesystem and
// subprocesses for scaffolding, building, discovering, activating and
// deactivating decoder plugins. gta-mcp is a pure forwarder to this service; in
// production the service runs as the standalone gta-plugin-dev binary,
// physically isolating all development capabilities from the runtime.
type PluginDevClient interface {
	// Scaffold renders the create_plugin skeleton and writes it under the
	// server's configured plugins directory as <name>/.
	Scaffold(ctx context.Context, in *ScaffoldRequest, opts ...grpc.CallOption) (*ScaffoldResponse, error)
	// ListPlugins returns plugins discovered on disk under the server's
	// configured plugins directory.
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// Build compiles a scaffolded plugin project, returning structured errors.
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
	// Activate launches a local plugin binary and registers it with the runtime.
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	// Deactivate stops a plugin process the Developer Plane launched.
	Deactivate(ctx context.Context, in *DeactivateRequest, opts ...grpc.CallOption) (*DeactivateResponse, error)
	// Status returns the Developer Plane portion of a plugin's dual-state view
	// (artifact from disk, the dev-launched process, and the last attempt).
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type pluginDevClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginDevClient(cc grpc.ClientConnInterface) PluginDevClient {
	return &pluginDevClient{cc}
}

func (c *pluginDevClient) Scaffold(ctx context.Context, in *ScaffoldRequest, opts ...grpc.CallOption) (*ScaffoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaffoldResponse)
	err := c.cc.Invoke(ctx, PluginDev_Scaffold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDevClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, PluginDev_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDevClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, PluginDev_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDevClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, PluginDev_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDevClient) Deactivate(ctx context.Context, in *DeactivateRequest, opts ...grpc.CallOption) (*DeactivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateResponse)
	err := c.cc.Invoke(ctx, PluginDev_Deactivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDevClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PluginDev_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginDevServer is the server API for PluginDev service.
// All implementations must embed UnimplementedPluginDevServer
// for forward compatibility.
//
// PluginDev is the Developer Plane control surface. It owns the filesystem and
// subprocesses for scaffolding, building, discovering, activating and
// deactivating decoder plugins. gta-mcp is a pure forwarder to this service; in
// production the service runs as the standalone gta-plugin-dev binary,
// physically isolating all development capabilities from the runtime.
type PluginDevServer interface {
	// Scaffold renders the create_plugin skeleton and writes it under the
	// server's configured plugins directory as <name>/.
	Scaffold(context.Context, *ScaffoldRequest) (*ScaffoldResponse, error)
	// ListPlugins returns plugins discovered on disk under the server's
	// configured plugins directory.
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// Build compiles a scaffolded plugin project, returning structured errors.
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	// Activate launches a local plugin binary and registers it with the runtime.
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	// Deactivate stops a plugin process the Developer Plane launched.
	Deactivate(context.Context, *DeactivateRequest) (*DeactivateResponse, error)
	// Status returns the Developer Plane portion of a plugin's dual-state view
	// (artifact from disk, the dev-launched process, and the last attempt).
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedPluginDevServer()
}

// UnimplementedPluginDevServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginDevServer struct{}

func (UnimplementedPluginDevServer) Scaffold(context.Context, *ScaffoldRequest) (*ScaffoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scaffold not implemented")
}
func (UnimplementedPluginDevServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedPluginDevServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedPluginDevServer) Activate(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedPluginDevServer) Deactivate(context.Context, *DeactivateRequest) (*DeactivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deactivate not implemented")
}
func (UnimplementedPluginDevServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPluginDevServer) mustEmbedUnimplementedPluginDevServer() {}
func (UnimplementedPluginDevServer) testEmbeddedByValue()                   {}

// UnsafePluginDevServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginDevServer will
// result in compilation errors.
type UnsafePluginDevServer interface {
	mustEmbedUnimplementedPluginDevServer()
}

func RegisterPluginDevServer(s grpc.ServiceRegistrar, srv PluginDevServer) {
	// If the following call panics, it indicates UnimplementedPluginDevServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginDev_ServiceDesc, srv)
}

func _PluginDev_Scaffold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaffoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDevServer).Scaffold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginDev_Scaffold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDevServer).Scaffold(ctx, req.(*ScaffoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDev_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDevServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginDev_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDevServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDev_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDevServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginDev_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDevServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDev_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDevServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginDev_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDevServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDev_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDevServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginDev_Deactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDevServer).Deactivate(ctx, req.(*DeactivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDev_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDevServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginDev_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDevServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginDev_ServiceDesc is the grpc.ServiceDesc for PluginDev service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginDev_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gta.plugindev.PluginDev",
	HandlerType: (*PluginDevServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scaffold",
			Handler:    _PluginDev_Scaffold_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _PluginDev_ListPlugins_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _PluginDev_Build_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _PluginDev_Activate_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _PluginDev_Deactivate_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _PluginDev_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugindev/proto/plugindev.proto",
}
