// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: pkg/plugindev/proto/plugindev.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScaffoldRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol        string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Hints           []string               `protobuf:"bytes,4,rep,name=hints,proto3" json:"hints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScaffoldRequest) Reset() {
	*x = ScaffoldRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaffoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaffoldRequest) ProtoMessage() {}

func (x *ScaffoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaffoldRequest.ProtoReflect.Descriptor instead.
func (*ScaffoldRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{0}
}

func (x *ScaffoldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaffoldRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ScaffoldRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ScaffoldRequest) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

type ScaffoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OutputDir     string                 `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	Created       []string               `protobuf:"bytes,3,rep,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaffoldResponse) Reset() {
	*x = ScaffoldResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaffoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaffoldResponse) ProtoMessage() {}

func (x *ScaffoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaffoldResponse.ProtoReflect.Descriptor instead.
func (*ScaffoldResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{1}
}

func (x *ScaffoldResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaffoldResponse) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *ScaffoldResponse) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{2}
}

type DiscoveredPlugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Binary        string                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredPlugin) Reset() {
	*x = DiscoveredPlugin{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredPlugin) ProtoMessage() {}

func (x *DiscoveredPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredPlugin.ProtoReflect.Descriptor instead.
func (*DiscoveredPlugin) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveredPlugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscoveredPlugin) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *DiscoveredPlugin) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*DiscoveredPlugin    `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{4}
}

func (x *ListPluginsResponse) GetPlugins() []*DiscoveredPlugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,2,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{5}
}

func (x *BuildRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type BuildError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildError) Reset() {
	*x = BuildError{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildError) ProtoMessage() {}

func (x *BuildError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildError.ProtoReflect.Descriptor instead.
func (*BuildError) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{6}
}

func (x *BuildError) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *BuildError) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *BuildError) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *BuildError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Errors        []*BuildError          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{7}
}

func (x *BuildResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BuildResponse) GetErrors() []*BuildError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BuildResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RegistryAddr  string                 `protobuf:"bytes,2,opt,name=registry_addr,json=registryAddr,proto3" json:"registry_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{8}
}

func (x *ActivateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivateRequest) GetRegistryAddr() string {
	if x != nil {
		return x.RegistryAddr
	}
	return ""
}

type ActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{9}
}

func (x *ActivateResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ActivateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ActivateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeactivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRequest) Reset() {
	*x = DeactivateRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRequest) ProtoMessage() {}

func (x *DeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{10}
}

func (x *DeactivateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeactivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateResponse) Reset() {
	*x = DeactivateResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateResponse) ProtoMessage() {}

func (x *DeactivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateResponse.ProtoReflect.Descriptor instead.
func (*DeactivateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{11}
}

func (x *DeactivateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeactivateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{12}
}

func (x *StatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ArtifactState is the Developer Plane's disk-derived view of the code.
type ArtifactState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // unknown | scaffolded | compiled | validated
	SourceDir     string                 `protobuf:"bytes,2,opt,name=source_dir,json=sourceDir,proto3" json:"source_dir,omitempty"`
	BinaryPath    string                 `protobuf:"bytes,3,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	BinaryStale   bool                   `protobuf:"varint,4,opt,name=binary_stale,json=binaryStale,proto3" json:"binary_stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactState) Reset() {
	*x = ArtifactState{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactState) ProtoMessage() {}

func (x *ArtifactState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactState.ProtoReflect.Descriptor instead.
func (*ArtifactState) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{13}
}

func (x *ArtifactState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ArtifactState) GetSourceDir() string {
	if x != nil {
		return x.SourceDir
	}
	return ""
}

func (x *ArtifactState) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *ArtifactState) GetBinaryStale() bool {
	if x != nil {
		return x.BinaryStale
	}
	return false
}

// DevProcess is the Developer Plane's view of the process it launched.
type DevProcess struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Launched       bool                   `protobuf:"varint,1,opt,name=launched,proto3" json:"launched,omitempty"`
	Pid            int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	InstanceId     string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Alive          bool                   `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	LaunchedAtUnix int64                  `protobuf:"varint,5,opt,name=launched_at_unix,json=launchedAtUnix,proto3" json:"launched_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DevProcess) Reset() {
	*x = DevProcess{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevProcess) ProtoMessage() {}

func (x *DevProcess) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevProcess.ProtoReflect.Descriptor instead.
func (*DevProcess) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{14}
}

func (x *DevProcess) GetLaunched() bool {
	if x != nil {
		return x.Launched
	}
	return false
}

func (x *DevProcess) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DevProcess) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DevProcess) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *DevProcess) GetLaunchedAtUnix() int64 {
	if x != nil {
		return x.LaunchedAtUnix
	}
	return 0
}

// LastAttempt is the most recent build/activate/deactivate outcome, used for
// failure attribution (design §2.3).
type LastAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // build | activate | deactivate
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	AtUnix        int64                  `protobuf:"varint,3,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Errors        []*BuildError          `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ExplainRef    string                 `protobuf:"bytes,7,opt,name=explain_ref,json=explainRef,proto3" json:"explain_ref,omitempty"` // P3a: points at a plugin.explain conclusion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastAttempt) Reset() {
	*x = LastAttempt{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastAttempt) ProtoMessage() {}

func (x *LastAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastAttempt.ProtoReflect.Descriptor instead.
func (*LastAttempt) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{15}
}

func (x *LastAttempt) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LastAttempt) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LastAttempt) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

func (x *LastAttempt) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *LastAttempt) GetErrors() []*BuildError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *LastAttempt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LastAttempt) GetExplainRef() string {
	if x != nil {
		return x.ExplainRef
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artifact      *ArtifactState         `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	DevProcess    *DevProcess            `protobuf:"bytes,3,opt,name=dev_process,json=devProcess,proto3" json:"dev_process,omitempty"`
	LastAttempt   *LastAttempt           `protobuf:"bytes,4,opt,name=last_attempt,json=lastAttempt,proto3" json:"last_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{16}
}

func (x *StatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse) GetArtifact() *ArtifactState {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *StatusResponse) GetDevProcess() *DevProcess {
	if x != nil {
		return x.DevProcess
	}
	return nil
}

func (x *StatusResponse) GetLastAttempt() *LastAttempt {
	if x != nil {
		return x.LastAttempt
	}
	return nil
}

// ExplainRequest asks for the attribution of a plugin's most recent failure.
type ExplainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional: which attempt to explain (build | activate | deactivate |
	// verify). If empty, the latest recorded attempt is explained.
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Optional: an inline verify result to attribute (decode-class failures,
	// P3b). When set, action is treated as "verify" and the result is classified
	// directly. When omitted on a verify request, the most recent result
	// recorded by plugin.verify (P4) via RecordVerify is used.
	Verify        *VerifyResult `protobuf:"bytes,3,opt,name=verify,proto3" json:"verify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{17}
}

func (x *ExplainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExplainRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExplainRequest) GetVerify() *VerifyResult {
	if x != nil {
		return x.Verify
	}
	return nil
}

// ExplainFinding is one attributed cause of failure.
type ExplainFinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set for build failures (the structured compiler diagnostic). Nil for
	// activation/process failures, which carry their cause in `why`.
	Error *BuildError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Machine category, e.g. undefined-symbol | type-mismatch | import | module |
	// syntax | binary-missing | process-crash | already-active | start-failed.
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Optional SDK contract rule_id (SSOT: contract.yaml rules: section) so the
	// AI can cross-reference the same vocabulary used by brief/verify.
	RuleId string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// Human explanation of why this failure happened.
	Why string `protobuf:"bytes,4,opt,name=why,proto3" json:"why,omitempty"`
	// Actionable corrective step.
	Fix           string `protobuf:"bytes,5,opt,name=fix,proto3" json:"fix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainFinding) Reset() {
	*x = ExplainFinding{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainFinding) ProtoMessage() {}

func (x *ExplainFinding) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainFinding.ProtoReflect.Descriptor instead.
func (*ExplainFinding) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{18}
}

func (x *ExplainFinding) GetError() *BuildError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExplainFinding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExplainFinding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ExplainFinding) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *ExplainFinding) GetFix() string {
	if x != nil {
		return x.Fix
	}
	return ""
}

// ExplainResponse is the conclusion of a plugin.explain invocation. Its `ref`
// is what last_attempt.explain_ref points back to.
type ExplainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"` // explain_ref, e.g. expl_<id>
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	AtUnix        int64                  `protobuf:"varint,4,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Findings      []*ExplainFinding      `protobuf:"bytes,6,rep,name=findings,proto3" json:"findings,omitempty"`
	NextAction    string                 `protobuf:"bytes,7,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"` // human-readable next step
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{19}
}

func (x *ExplainResponse) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ExplainResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExplainResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExplainResponse) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

func (x *ExplainResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ExplainResponse) GetFindings() []*ExplainFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ExplainResponse) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

// VerifyResult is the output of plugin.verify (P4): SDK contract violations,
// gta-side quality statistics, and an overall verdict. plugin.explain (P3b)
// consumes it to attribute decode-class failures (all-unknown / wrong framing /
// suspected encryption / suspected missing reassembly).
type VerifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Violations    []*Violation           `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	Quality       *QualityStats          `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Verdict       string                 `protobuf:"bytes,3,opt,name=verdict,proto3" json:"verdict,omitempty"` // pass | warn | fail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResult) Reset() {
	*x = VerifyResult{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResult) ProtoMessage() {}

func (x *VerifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResult.ProtoReflect.Descriptor instead.
func (*VerifyResult) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyResult) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *VerifyResult) GetQuality() *QualityStats {
	if x != nil {
		return x.Quality
	}
	return nil
}

func (x *VerifyResult) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

// Violation is a single SDK contract rule the verify corpus tripped. rule_id is
// the shared vocabulary defined in contract.yaml (rules: section) and reused by
// brief / verify / explain.
type Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Statement     string                 `protobuf:"bytes,4,opt,name=statement,proto3" json:"statement,omitempty"`
	DocRef        string                 `protobuf:"bytes,5,opt,name=doc_ref,json=docRef,proto3" json:"doc_ref,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Sample        string                 `protobuf:"bytes,7,opt,name=sample,proto3" json:"sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{21}
}

func (x *Violation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Violation) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Violation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Violation) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *Violation) GetDocRef() string {
	if x != nil {
		return x.DocRef
	}
	return ""
}

func (x *Violation) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Violation) GetSample() string {
	if x != nil {
		return x.Sample
	}
	return ""
}

// QualityStats holds the corpus-level signals plugin.explain classifies. All
// fields are optional; a missing QualityStats means no statistical evidence is
// available and explain falls back to violations only.
type QualityStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalInputs          int32                  `protobuf:"varint,1,opt,name=total_inputs,json=totalInputs,proto3" json:"total_inputs,omitempty"`
	UnknownInputs        int32                  `protobuf:"varint,2,opt,name=unknown_inputs,json=unknownInputs,proto3" json:"unknown_inputs,omitempty"`
	UnknownRatio         float64                `protobuf:"fixed64,3,opt,name=unknown_ratio,json=unknownRatio,proto3" json:"unknown_ratio,omitempty"`
	CorrelatedInputs     int32                  `protobuf:"varint,4,opt,name=correlated_inputs,json=correlatedInputs,proto3" json:"correlated_inputs,omitempty"`
	LongPacketErrors     int32                  `protobuf:"varint,5,opt,name=long_packet_errors,json=longPacketErrors,proto3" json:"long_packet_errors,omitempty"`
	EntropyEstimate      float64                `protobuf:"fixed64,6,opt,name=entropy_estimate,json=entropyEstimate,proto3" json:"entropy_estimate,omitempty"`
	SchemaVersionedRatio float64                `protobuf:"fixed64,7,opt,name=schema_versioned_ratio,json=schemaVersionedRatio,proto3" json:"schema_versioned_ratio,omitempty"`
	DecodeErrors         int32                  `protobuf:"varint,8,opt,name=decode_errors,json=decodeErrors,proto3" json:"decode_errors,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QualityStats) Reset() {
	*x = QualityStats{}
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityStats) ProtoMessage() {}

func (x *QualityStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugindev_proto_plugindev_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityStats.ProtoReflect.Descriptor instead.
func (*QualityStats) Descriptor() ([]byte, []int) {
	return file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP(), []int{22}
}

func (x *QualityStats) GetTotalInputs() int32 {
	if x != nil {
		return x.TotalInputs
	}
	return 0
}

func (x *QualityStats) GetUnknownInputs() int32 {
	if x != nil {
		return x.UnknownInputs
	}
	return 0
}

func (x *QualityStats) GetUnknownRatio() float64 {
	if x != nil {
		return x.UnknownRatio
	}
	return 0
}

func (x *QualityStats) GetCorrelatedInputs() int32 {
	if x != nil {
		return x.CorrelatedInputs
	}
	return 0
}

func (x *QualityStats) GetLongPacketErrors() int32 {
	if x != nil {
		return x.LongPacketErrors
	}
	return 0
}

func (x *QualityStats) GetEntropyEstimate() float64 {
	if x != nil {
		return x.EntropyEstimate
	}
	return 0
}

func (x *QualityStats) GetSchemaVersionedRatio() float64 {
	if x != nil {
		return x.SchemaVersionedRatio
	}
	return 0
}

func (x *QualityStats) GetDecodeErrors() int32 {
	if x != nil {
		return x.DecodeErrors
	}
	return 0
}

var File_pkg_plugindev_proto_plugindev_proto protoreflect.FileDescriptor

const file_pkg_plugindev_proto_plugindev_proto_rawDesc = "" +
	"\n" +
	"#pkg/plugindev/proto/plugindev.proto\x12\rgta.plugindev\"\x82\x01\n" +
	"\x0fScaffoldRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12\x14\n" +
	"\x05hints\x18\x04 \x03(\tR\x05hints\"_\n" +
	"\x10ScaffoldResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\x12\x18\n" +
	"\acreated\x18\x03 \x03(\tR\acreated\"\x14\n" +
	"\x12ListPluginsRequest\"P\n" +
	"\x10DiscoveredPlugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\tR\x06binary\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\"P\n" +
	"\x13ListPluginsResponse\x129\n" +
	"\aplugins\x18\x01 \x03(\v2\x1f.gta.plugindev.DiscoveredPluginR\aplugins\"C\n" +
	"\fBuildRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vtimeout_sec\x18\x02 \x01(\x05R\n" +
	"timeoutSec\"`\n" +
	"\n" +
	"BuildError\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"j\n" +
	"\rBuildResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\x06errors\x18\x02 \x03(\v2\x19.gta.plugindev.BuildErrorR\x06errors\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"J\n" +
	"\x0fActivateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rregistry_addr\x18\x02 \x01(\tR\fregistryAddr\"]\n" +
	"\x10ActivateResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"'\n" +
	"\x11DeactivateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\x12DeactivateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x88\x01\n" +
	"\rArtifactState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"source_dir\x18\x02 \x01(\tR\tsourceDir\x12\x1f\n" +
	"\vbinary_path\x18\x03 \x01(\tR\n" +
	"binaryPath\x12!\n" +
	"\fbinary_stale\x18\x04 \x01(\bR\vbinaryStale\"\x9b\x01\n" +
	"\n" +
	"DevProcess\x12\x1a\n" +
	"\blaunched\x18\x01 \x01(\bR\blaunched\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05alive\x18\x04 \x01(\bR\x05alive\x12(\n" +
	"\x10launched_at_unix\x18\x05 \x01(\x03R\x0elaunchedAtUnix\"\xdd\x01\n" +
	"\vLastAttempt\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x17\n" +
	"\aat_unix\x18\x03 \x01(\x03R\x06atUnix\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x121\n" +
	"\x06errors\x18\x05 \x03(\v2\x19.gta.plugindev.BuildErrorR\x06errors\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1f\n" +
	"\vexplain_ref\x18\a \x01(\tR\n" +
	"explainRef\"\xd9\x01\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\bartifact\x18\x02 \x01(\v2\x1c.gta.plugindev.ArtifactStateR\bartifact\x12:\n" +
	"\vdev_process\x18\x03 \x01(\v2\x19.gta.plugindev.DevProcessR\n" +
	"devProcess\x12=\n" +
	"\flast_attempt\x18\x04 \x01(\v2\x1a.gta.plugindev.LastAttemptR\vlastAttempt\"q\n" +
	"\x0eExplainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x123\n" +
	"\x06verify\x18\x03 \x01(\v2\x1b.gta.plugindev.VerifyResultR\x06verify\"\x9a\x01\n" +
	"\x0eExplainFinding\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.gta.plugindev.BuildErrorR\x05error\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12\x10\n" +
	"\x03why\x18\x04 \x01(\tR\x03why\x12\x10\n" +
	"\x03fix\x18\x05 \x01(\tR\x03fix\"\xde\x01\n" +
	"\x0fExplainResponse\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x17\n" +
	"\aat_unix\x18\x04 \x01(\x03R\x06atUnix\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x129\n" +
	"\bfindings\x18\x06 \x03(\v2\x1d.gta.plugindev.ExplainFindingR\bfindings\x12\x1f\n" +
	"\vnext_action\x18\a \x01(\tR\n" +
	"nextAction\"\x99\x01\n" +
	"\fVerifyResult\x128\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2\x18.gta.plugindev.ViolationR\n" +
	"violations\x125\n" +
	"\aquality\x18\x02 \x01(\v2\x1b.gta.plugindev.QualityStatsR\aquality\x12\x18\n" +
	"\averdict\x18\x03 \x01(\tR\averdict\"\xbb\x01\n" +
	"\tViolation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1c\n" +
	"\tstatement\x18\x04 \x01(\tR\tstatement\x12\x17\n" +
	"\adoc_ref\x18\x05 \x01(\tR\x06docRef\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x16\n" +
	"\x06sample\x18\a \x01(\tR\x06sample\"\xde\x02\n" +
	"\fQualityStats\x12!\n" +
	"\ftotal_inputs\x18\x01 \x01(\x05R\vtotalInputs\x12%\n" +
	"\x0eunknown_inputs\x18\x02 \x01(\x05R\runknownInputs\x12#\n" +
	"\runknown_ratio\x18\x03 \x01(\x01R\funknownRatio\x12+\n" +
	"\x11correlated_inputs\x18\x04 \x01(\x05R\x10correlatedInputs\x12,\n" +
	"\x12long_packet_errors\x18\x05 \x01(\x05R\x10longPacketErrors\x12)\n" +
	"\x10entropy_estimate\x18\x06 \x01(\x01R\x0fentropyEstimate\x124\n" +
	"\x16schema_versioned_ratio\x18\a \x01(\x01R\x14schemaVersionedRatio\x12#\n" +
	"\rdecode_errors\x18\b \x01(\x05R\fdecodeErrors2\xa3\x04\n" +
	"\tPluginDev\x12K\n" +
	"\bScaffold\x12\x1e.gta.plugindev.ScaffoldRequest\x1a\x1f.gta.plugindev.ScaffoldResponse\x12T\n" +
	"\vListPlugins\x12!.gta.plugindev.ListPluginsRequest\x1a\".gta.plugindev.ListPluginsResponse\x12B\n" +
	"\x05Build\x12\x1b.gta.plugindev.BuildRequest\x1a\x1c.gta.plugindev.BuildResponse\x12K\n" +
	"\bActivate\x12\x1e.gta.plugindev.ActivateRequest\x1a\x1f.gta.plugindev.ActivateResponse\x12Q\n" +
	"\n" +
	"Deactivate\x12 .gta.plugindev.DeactivateRequest\x1a!.gta.plugindev.DeactivateResponse\x12E\n" +
	"\x06Status\x12\x1c.gta.plugindev.StatusRequest\x1a\x1d.gta.plugindev.StatusResponse\x12H\n" +
	"\aExplain\x12\x1d.gta.plugindev.ExplainRequest\x1a\x1e.gta.plugindev.ExplainResponseB\x19Z\x17gta/pkg/plugindev/protob\x06proto3"

var (
	file_pkg_plugindev_proto_plugindev_proto_rawDescOnce sync.Once
	file_pkg_plugindev_proto_plugindev_proto_rawDescData []byte
)

func file_pkg_plugindev_proto_plugindev_proto_rawDescGZIP() []byte {
	file_pkg_plugindev_proto_plugindev_proto_rawDescOnce.Do(func() {
		file_pkg_plugindev_proto_plugindev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugindev_proto_plugindev_proto_rawDesc), len(file_pkg_plugindev_proto_plugindev_proto_rawDesc)))
	})
	return file_pkg_plugindev_proto_plugindev_proto_rawDescData
}

var file_pkg_plugindev_proto_plugindev_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_plugindev_proto_plugindev_proto_goTypes = []any{
	(*ScaffoldRequest)(nil),     // 0: gta.plugindev.ScaffoldRequest
	(*ScaffoldResponse)(nil),    // 1: gta.plugindev.ScaffoldResponse
	(*ListPluginsRequest)(nil),  // 2: gta.plugindev.ListPluginsRequest
	(*DiscoveredPlugin)(nil),    // 3: gta.plugindev.DiscoveredPlugin
	(*ListPluginsResponse)(nil), // 4: gta.plugindev.ListPluginsResponse
	(*BuildRequest)(nil),        // 5: gta.plugindev.BuildRequest
	(*BuildError)(nil),          // 6: gta.plugindev.BuildError
	(*BuildResponse)(nil),       // 7: gta.plugindev.BuildResponse
	(*ActivateRequest)(nil),     // 8: gta.plugindev.ActivateRequest
	(*ActivateResponse)(nil),    // 9: gta.plugindev.ActivateResponse
	(*DeactivateRequest)(nil),   // 10: gta.plugindev.DeactivateRequest
	(*DeactivateResponse)(nil),  // 11: gta.plugindev.DeactivateResponse
	(*StatusRequest)(nil),       // 12: gta.plugindev.StatusRequest
	(*ArtifactState)(nil),       // 13: gta.plugindev.ArtifactState
	(*DevProcess)(nil),          // 14: gta.plugindev.DevProcess
	(*LastAttempt)(nil),         // 15: gta.plugindev.LastAttempt
	(*StatusResponse)(nil),      // 16: gta.plugindev.StatusResponse
	(*ExplainRequest)(nil),      // 17: gta.plugindev.ExplainRequest
	(*ExplainFinding)(nil),      // 18: gta.plugindev.ExplainFinding
	(*ExplainResponse)(nil),     // 19: gta.plugindev.ExplainResponse
	(*VerifyResult)(nil),        // 20: gta.plugindev.VerifyResult
	(*Violation)(nil),           // 21: gta.plugindev.Violation
	(*QualityStats)(nil),        // 22: gta.plugindev.QualityStats
}
var file_pkg_plugindev_proto_plugindev_proto_depIdxs = []int32{
	3,  // 0: gta.plugindev.ListPluginsResponse.plugins:type_name -> gta.plugindev.DiscoveredPlugin
	6,  // 1: gta.plugindev.BuildResponse.errors:type_name -> gta.plugindev.BuildError
	6,  // 2: gta.plugindev.LastAttempt.errors:type_name -> gta.plugindev.BuildError
	13, // 3: gta.plugindev.StatusResponse.artifact:type_name -> gta.plugindev.ArtifactState
	14, // 4: gta.plugindev.StatusResponse.dev_process:type_name -> gta.plugindev.DevProcess
	15, // 5: gta.plugindev.StatusResponse.last_attempt:type_name -> gta.plugindev.LastAttempt
	20, // 6: gta.plugindev.ExplainRequest.verify:type_name -> gta.plugindev.VerifyResult
	6,  // 7: gta.plugindev.ExplainFinding.error:type_name -> gta.plugindev.BuildError
	18, // 8: gta.plugindev.ExplainResponse.findings:type_name -> gta.plugindev.ExplainFinding
	21, // 9: gta.plugindev.VerifyResult.violations:type_name -> gta.plugindev.Violation
	22, // 10: gta.plugindev.VerifyResult.quality:type_name -> gta.plugindev.QualityStats
	0,  // 11: gta.plugindev.PluginDev.Scaffold:input_type -> gta.plugindev.ScaffoldRequest
	2,  // 12: gta.plugindev.PluginDev.ListPlugins:input_type -> gta.plugindev.ListPluginsRequest
	5,  // 13: gta.plugindev.PluginDev.Build:input_type -> gta.plugindev.BuildRequest
	8,  // 14: gta.plugindev.PluginDev.Activate:input_type -> gta.plugindev.ActivateRequest
	10, // 15: gta.plugindev.PluginDev.Deactivate:input_type -> gta.plugindev.DeactivateRequest
	12, // 16: gta.plugindev.PluginDev.Status:input_type -> gta.plugindev.StatusRequest
	17, // 17: gta.plugindev.PluginDev.Explain:input_type -> gta.plugindev.ExplainRequest
	1,  // 18: gta.plugindev.PluginDev.Scaffold:output_type -> gta.plugindev.ScaffoldResponse
	4,  // 19: gta.plugindev.PluginDev.ListPlugins:output_type -> gta.plugindev.ListPluginsResponse
	7,  // 20: gta.plugindev.PluginDev.Build:output_type -> gta.plugindev.BuildResponse
	9,  // 21: gta.plugindev.PluginDev.Activate:output_type -> gta.plugindev.ActivateResponse
	11, // 22: gta.plugindev.PluginDev.Deactivate:output_type -> gta.plugindev.DeactivateResponse
	16, // 23: gta.plugindev.PluginDev.Status:output_type -> gta.plugindev.StatusResponse
	19, // 24: gta.plugindev.PluginDev.Explain:output_type -> gta.plugindev.ExplainResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_plugindev_proto_plugindev_proto_init() }
func file_pkg_plugindev_proto_plugindev_proto_init() {
	if File_pkg_plugindev_proto_plugindev_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugindev_proto_plugindev_proto_rawDesc), len(file_pkg_plugindev_proto_plugindev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugindev_proto_plugindev_proto_goTypes,
		DependencyIndexes: file_pkg_plugindev_proto_plugindev_proto_depIdxs,
		MessageInfos:      file_pkg_plugindev_proto_plugindev_proto_msgTypes,
	}.Build()
	File_pkg_plugindev_proto_plugindev_proto = out.File
	file_pkg_plugindev_proto_plugindev_proto_goTypes = nil
	file_pkg_plugindev_proto_plugindev_proto_depIdxs = nil
}
