// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: pkg/internalipc/proto/internal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaptureControl_StartCapture_FullMethodName        = "/gta.internalipc.CaptureControl/StartCapture"
	CaptureControl_StopCapture_FullMethodName         = "/gta.internalipc.CaptureControl/StopCapture"
	CaptureControl_GetCaptureStatus_FullMethodName    = "/gta.internalipc.CaptureControl/GetCaptureStatus"
	CaptureControl_ListCaptureSessions_FullMethodName = "/gta.internalipc.CaptureControl/ListCaptureSessions"
	CaptureControl_ListInterfaces_FullMethodName      = "/gta.internalipc.CaptureControl/ListInterfaces"
	CaptureControl_DecodeRawPackets_FullMethodName    = "/gta.internalipc.CaptureControl/DecodeRawPackets"
	CaptureControl_ListPlugins_FullMethodName         = "/gta.internalipc.CaptureControl/ListPlugins"
	CaptureControl_GetPluginManifest_FullMethodName   = "/gta.internalipc.CaptureControl/GetPluginManifest"
	CaptureControl_DeregisterPlugin_FullMethodName    = "/gta.internalipc.CaptureControl/DeregisterPlugin"
	CaptureControl_SetSessionPlugin_FullMethodName    = "/gta.internalipc.CaptureControl/SetSessionPlugin"
	CaptureControl_WatchPlugins_FullMethodName        = "/gta.internalipc.CaptureControl/WatchPlugins"
	CaptureControl_TestPlugin_FullMethodName          = "/gta.internalipc.CaptureControl/TestPlugin"
	CaptureControl_Verify_FullMethodName              = "/gta.internalipc.CaptureControl/Verify"
	CaptureControl_SampleBytes_FullMethodName         = "/gta.internalipc.CaptureControl/SampleBytes"
	CaptureControl_GetRegistryAddr_FullMethodName     = "/gta.internalipc.CaptureControl/GetRegistryAddr"
)

// CaptureControlClient is the client API for CaptureControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptureControl 由 gta-pipeline 进程提供，gta-mcp 作为 client 调用。
// 仅控制面 unary RPC，无 streaming。数据面走 SQLite。
type CaptureControlClient interface {
	// StartCapture 启动一次抓包会话。
	StartCapture(ctx context.Context, in *StartCaptureRequest, opts ...grpc.CallOption) (*StartCaptureResponse, error)
	// StopCapture 停止当前抓包会话。
	StopCapture(ctx context.Context, in *StopCaptureRequest, opts ...grpc.CallOption) (*StopCaptureResponse, error)
	// GetCaptureStatus 查询抓包状态与统计。
	GetCaptureStatus(ctx context.Context, in *GetCaptureStatusRequest, opts ...grpc.CallOption) (*GetCaptureStatusResponse, error)
	// ListCaptureSessions 列出当前活跃的抓包会话。
	ListCaptureSessions(ctx context.Context, in *ListCaptureSessionsRequest, opts ...grpc.CallOption) (*ListCaptureSessionsResponse, error)
	// ListInterfaces 列出可用网卡。
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	// DecodeRawPackets 用指定插件对离线会话的 raw_packets 批量解码，
	// 结果写入该 session 的 events 表。
	DecodeRawPackets(ctx context.Context, in *DecodeRawPacketsRequest, opts ...grpc.CallOption) (*DecodeRawPacketsResponse, error)
	// ListPlugins 列出当前已注册的插件摘要。
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// GetPluginManifest 获取指定插件的 manifest bytes（plugin.yaml 原始内容）。
	GetPluginManifest(ctx context.Context, in *GetPluginManifestRequest, opts ...grpc.CallOption) (*GetPluginManifestResponse, error)
	// DeregisterPlugin 注销指定插件（按 instance_id 或 name）。
	DeregisterPlugin(ctx context.Context, in *DeregisterPluginRequest, opts ...grpc.CallOption) (*DeregisterPluginResponse, error)
	// SetSessionPlugin 运行中热切换某抓包会话的解码插件绑定。
	// 切换后立即触发解码器重解析，无需停止再重启抓包。
	SetSessionPlugin(ctx context.Context, in *SetSessionPluginRequest, opts ...grpc.CallOption) (*SetSessionPluginResponse, error)
	// WatchPlugins 服务端流式推送插件注册表状态变化（register/deregister/online/offline）。
	// 用于前端即时刷新插件面板、以及抓包侧即时感知插件上下线，避免轮询延迟。
	WatchPlugins(ctx context.Context, in *WatchPluginsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PluginEvent], error)
	// TestPlugin 用指定插件对离线会话的 raw_packets 解码并采样返回，用于验证插件解码质量。
	// 原始包字节仅进程内使用，绝不回传前端；结果不落库（隔离测试，不污染会话真实解码数据）。
	// 该能力不暴露原始包，因此无需 --enable-raw-debug 门控。
	TestPlugin(ctx context.Context, in *TestPluginRequest, opts ...grpc.CallOption) (*TestPluginResponse, error)
	// Verify 用指定插件对离线会话的 raw_packets 解码并做契约+质量校验，
	// 产出 violations（引 SDK checker，带 rule_id）+ quality（gta 统计）+ verdict。
	// 仅统计不落库；validated 证明写入 Developer Plane 的 Tracker（跨平面）。
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// SampleBytes 读取会话原始包的前若干字节（事实：hexdump/长度直方图/首字节分布/熵），
	// 不解释，并在 plugin_debug_access 留审计。硬上限由服务端强制（20 包 / 64 字节）。
	SampleBytes(ctx context.Context, in *SampleBytesRequest, opts ...grpc.CallOption) (*SampleBytesResponse, error)
	// GetRegistryAddr 返回插件应连接注册中心地址（即 -registry-addr 的值，如 :9091）。
	// gta-mcp 与插件启动时需要此地址填入 GTA_REGISTRY_ADDR；此前只能由人工从
	// 启动日志中获取。改为由 pipeline 通过本 RPC 直接暴露，避免插件「不知道该连哪里」。
	GetRegistryAddr(ctx context.Context, in *GetRegistryAddrRequest, opts ...grpc.CallOption) (*GetRegistryAddrResponse, error)
}

type captureControlClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureControlClient(cc grpc.ClientConnInterface) CaptureControlClient {
	return &captureControlClient{cc}
}

func (c *captureControlClient) StartCapture(ctx context.Context, in *StartCaptureRequest, opts ...grpc.CallOption) (*StartCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_StartCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) StopCapture(ctx context.Context, in *StopCaptureRequest, opts ...grpc.CallOption) (*StopCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_StopCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetCaptureStatus(ctx context.Context, in *GetCaptureStatusRequest, opts ...grpc.CallOption) (*GetCaptureStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaptureStatusResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetCaptureStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListCaptureSessions(ctx context.Context, in *ListCaptureSessionsRequest, opts ...grpc.CallOption) (*ListCaptureSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCaptureSessionsResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListCaptureSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) DecodeRawPackets(ctx context.Context, in *DecodeRawPacketsRequest, opts ...grpc.CallOption) (*DecodeRawPacketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeRawPacketsResponse)
	err := c.cc.Invoke(ctx, CaptureControl_DecodeRawPackets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetPluginManifest(ctx context.Context, in *GetPluginManifestRequest, opts ...grpc.CallOption) (*GetPluginManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginManifestResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetPluginManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) DeregisterPlugin(ctx context.Context, in *DeregisterPluginRequest, opts ...grpc.CallOption) (*DeregisterPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterPluginResponse)
	err := c.cc.Invoke(ctx, CaptureControl_DeregisterPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) SetSessionPlugin(ctx context.Context, in *SetSessionPluginRequest, opts ...grpc.CallOption) (*SetSessionPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSessionPluginResponse)
	err := c.cc.Invoke(ctx, CaptureControl_SetSessionPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) WatchPlugins(ctx context.Context, in *WatchPluginsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PluginEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaptureControl_ServiceDesc.Streams[0], CaptureControl_WatchPlugins_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPluginsRequest, PluginEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureControl_WatchPluginsClient = grpc.ServerStreamingClient[PluginEvent]

func (c *captureControlClient) TestPlugin(ctx context.Context, in *TestPluginRequest, opts ...grpc.CallOption) (*TestPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestPluginResponse)
	err := c.cc.Invoke(ctx, CaptureControl_TestPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, CaptureControl_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) SampleBytes(ctx context.Context, in *SampleBytesRequest, opts ...grpc.CallOption) (*SampleBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleBytesResponse)
	err := c.cc.Invoke(ctx, CaptureControl_SampleBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetRegistryAddr(ctx context.Context, in *GetRegistryAddrRequest, opts ...grpc.CallOption) (*GetRegistryAddrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistryAddrResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetRegistryAddr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureControlServer is the server API for CaptureControl service.
// All implementations must embed UnimplementedCaptureControlServer
// for forward compatibility.
//
// CaptureControl 由 gta-pipeline 进程提供，gta-mcp 作为 client 调用。
// 仅控制面 unary RPC，无 streaming。数据面走 SQLite。
type CaptureControlServer interface {
	// StartCapture 启动一次抓包会话。
	StartCapture(context.Context, *StartCaptureRequest) (*StartCaptureResponse, error)
	// StopCapture 停止当前抓包会话。
	StopCapture(context.Context, *StopCaptureRequest) (*StopCaptureResponse, error)
	// GetCaptureStatus 查询抓包状态与统计。
	GetCaptureStatus(context.Context, *GetCaptureStatusRequest) (*GetCaptureStatusResponse, error)
	// ListCaptureSessions 列出当前活跃的抓包会话。
	ListCaptureSessions(context.Context, *ListCaptureSessionsRequest) (*ListCaptureSessionsResponse, error)
	// ListInterfaces 列出可用网卡。
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	// DecodeRawPackets 用指定插件对离线会话的 raw_packets 批量解码，
	// 结果写入该 session 的 events 表。
	DecodeRawPackets(context.Context, *DecodeRawPacketsRequest) (*DecodeRawPacketsResponse, error)
	// ListPlugins 列出当前已注册的插件摘要。
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// GetPluginManifest 获取指定插件的 manifest bytes（plugin.yaml 原始内容）。
	GetPluginManifest(context.Context, *GetPluginManifestRequest) (*GetPluginManifestResponse, error)
	// DeregisterPlugin 注销指定插件（按 instance_id 或 name）。
	DeregisterPlugin(context.Context, *DeregisterPluginRequest) (*DeregisterPluginResponse, error)
	// SetSessionPlugin 运行中热切换某抓包会话的解码插件绑定。
	// 切换后立即触发解码器重解析，无需停止再重启抓包。
	SetSessionPlugin(context.Context, *SetSessionPluginRequest) (*SetSessionPluginResponse, error)
	// WatchPlugins 服务端流式推送插件注册表状态变化（register/deregister/online/offline）。
	// 用于前端即时刷新插件面板、以及抓包侧即时感知插件上下线，避免轮询延迟。
	WatchPlugins(*WatchPluginsRequest, grpc.ServerStreamingServer[PluginEvent]) error
	// TestPlugin 用指定插件对离线会话的 raw_packets 解码并采样返回，用于验证插件解码质量。
	// 原始包字节仅进程内使用，绝不回传前端；结果不落库（隔离测试，不污染会话真实解码数据）。
	// 该能力不暴露原始包，因此无需 --enable-raw-debug 门控。
	TestPlugin(context.Context, *TestPluginRequest) (*TestPluginResponse, error)
	// Verify 用指定插件对离线会话的 raw_packets 解码并做契约+质量校验，
	// 产出 violations（引 SDK checker，带 rule_id）+ quality（gta 统计）+ verdict。
	// 仅统计不落库；validated 证明写入 Developer Plane 的 Tracker（跨平面）。
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// SampleBytes 读取会话原始包的前若干字节（事实：hexdump/长度直方图/首字节分布/熵），
	// 不解释，并在 plugin_debug_access 留审计。硬上限由服务端强制（20 包 / 64 字节）。
	SampleBytes(context.Context, *SampleBytesRequest) (*SampleBytesResponse, error)
	// GetRegistryAddr 返回插件应连接注册中心地址（即 -registry-addr 的值，如 :9091）。
	// gta-mcp 与插件启动时需要此地址填入 GTA_REGISTRY_ADDR；此前只能由人工从
	// 启动日志中获取。改为由 pipeline 通过本 RPC 直接暴露，避免插件「不知道该连哪里」。
	GetRegistryAddr(context.Context, *GetRegistryAddrRequest) (*GetRegistryAddrResponse, error)
	mustEmbedUnimplementedCaptureControlServer()
}

// UnimplementedCaptureControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureControlServer struct{}

func (UnimplementedCaptureControlServer) StartCapture(context.Context, *StartCaptureRequest) (*StartCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCapture not implemented")
}
func (UnimplementedCaptureControlServer) StopCapture(context.Context, *StopCaptureRequest) (*StopCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopCapture not implemented")
}
func (UnimplementedCaptureControlServer) GetCaptureStatus(context.Context, *GetCaptureStatusRequest) (*GetCaptureStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCaptureStatus not implemented")
}
func (UnimplementedCaptureControlServer) ListCaptureSessions(context.Context, *ListCaptureSessionsRequest) (*ListCaptureSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCaptureSessions not implemented")
}
func (UnimplementedCaptureControlServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedCaptureControlServer) DecodeRawPackets(context.Context, *DecodeRawPacketsRequest) (*DecodeRawPacketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeRawPackets not implemented")
}
func (UnimplementedCaptureControlServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedCaptureControlServer) GetPluginManifest(context.Context, *GetPluginManifestRequest) (*GetPluginManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginManifest not implemented")
}
func (UnimplementedCaptureControlServer) DeregisterPlugin(context.Context, *DeregisterPluginRequest) (*DeregisterPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterPlugin not implemented")
}
func (UnimplementedCaptureControlServer) SetSessionPlugin(context.Context, *SetSessionPluginRequest) (*SetSessionPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSessionPlugin not implemented")
}
func (UnimplementedCaptureControlServer) WatchPlugins(*WatchPluginsRequest, grpc.ServerStreamingServer[PluginEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPlugins not implemented")
}
func (UnimplementedCaptureControlServer) TestPlugin(context.Context, *TestPluginRequest) (*TestPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestPlugin not implemented")
}
func (UnimplementedCaptureControlServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedCaptureControlServer) SampleBytes(context.Context, *SampleBytesRequest) (*SampleBytesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SampleBytes not implemented")
}
func (UnimplementedCaptureControlServer) GetRegistryAddr(context.Context, *GetRegistryAddrRequest) (*GetRegistryAddrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistryAddr not implemented")
}
func (UnimplementedCaptureControlServer) mustEmbedUnimplementedCaptureControlServer() {}
func (UnimplementedCaptureControlServer) testEmbeddedByValue()                        {}

// UnsafeCaptureControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureControlServer will
// result in compilation errors.
type UnsafeCaptureControlServer interface {
	mustEmbedUnimplementedCaptureControlServer()
}

func RegisterCaptureControlServer(s grpc.ServiceRegistrar, srv CaptureControlServer) {
	// If the following call panics, it indicates UnimplementedCaptureControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureControl_ServiceDesc, srv)
}

func _CaptureControl_StartCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).StartCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_StartCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).StartCapture(ctx, req.(*StartCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_StopCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).StopCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_StopCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).StopCapture(ctx, req.(*StopCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetCaptureStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptureStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetCaptureStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetCaptureStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetCaptureStatus(ctx, req.(*GetCaptureStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListCaptureSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCaptureSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListCaptureSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListCaptureSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListCaptureSessions(ctx, req.(*ListCaptureSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_DecodeRawPackets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRawPacketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).DecodeRawPackets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_DecodeRawPackets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).DecodeRawPackets(ctx, req.(*DecodeRawPacketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetPluginManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetPluginManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetPluginManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetPluginManifest(ctx, req.(*GetPluginManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_DeregisterPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).DeregisterPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_DeregisterPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).DeregisterPlugin(ctx, req.(*DeregisterPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_SetSessionPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSessionPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).SetSessionPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_SetSessionPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).SetSessionPlugin(ctx, req.(*SetSessionPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_WatchPlugins_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPluginsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaptureControlServer).WatchPlugins(m, &grpc.GenericServerStream[WatchPluginsRequest, PluginEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureControl_WatchPluginsServer = grpc.ServerStreamingServer[PluginEvent]

func _CaptureControl_TestPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).TestPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_TestPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).TestPlugin(ctx, req.(*TestPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_SampleBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).SampleBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_SampleBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).SampleBytes(ctx, req.(*SampleBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetRegistryAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistryAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetRegistryAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetRegistryAddr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetRegistryAddr(ctx, req.(*GetRegistryAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptureControl_ServiceDesc is the grpc.ServiceDesc for CaptureControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gta.internalipc.CaptureControl",
	HandlerType: (*CaptureControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCapture",
			Handler:    _CaptureControl_StartCapture_Handler,
		},
		{
			MethodName: "StopCapture",
			Handler:    _CaptureControl_StopCapture_Handler,
		},
		{
			MethodName: "GetCaptureStatus",
			Handler:    _CaptureControl_GetCaptureStatus_Handler,
		},
		{
			MethodName: "ListCaptureSessions",
			Handler:    _CaptureControl_ListCaptureSessions_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _CaptureControl_ListInterfaces_Handler,
		},
		{
			MethodName: "DecodeRawPackets",
			Handler:    _CaptureControl_DecodeRawPackets_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _CaptureControl_ListPlugins_Handler,
		},
		{
			MethodName: "GetPluginManifest",
			Handler:    _CaptureControl_GetPluginManifest_Handler,
		},
		{
			MethodName: "DeregisterPlugin",
			Handler:    _CaptureControl_DeregisterPlugin_Handler,
		},
		{
			MethodName: "SetSessionPlugin",
			Handler:    _CaptureControl_SetSessionPlugin_Handler,
		},
		{
			MethodName: "TestPlugin",
			Handler:    _CaptureControl_TestPlugin_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _CaptureControl_Verify_Handler,
		},
		{
			MethodName: "SampleBytes",
			Handler:    _CaptureControl_SampleBytes_Handler,
		},
		{
			MethodName: "GetRegistryAddr",
			Handler:    _CaptureControl_GetRegistryAddr_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPlugins",
			Handler:       _CaptureControl_WatchPlugins_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/internalipc/proto/internal.proto",
}
