// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: pkg/internalipc/proto/internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecodeRawPacketsRequest 离线解码请求。
// session_id 指定待解码的会话；plugin 指定解码插件（必填）。
// protocol/src/dst/limit 为可选过滤条件，限定解码范围。
// clear_existing 为 true 时先清空该 session 的 events 再写入。
type DecodeRawPacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Src           string                 `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	ClearExisting bool                   `protobuf:"varint,7,opt,name=clear_existing,json=clearExisting,proto3" json:"clear_existing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRawPacketsRequest) Reset() {
	*x = DecodeRawPacketsRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRawPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRawPacketsRequest) ProtoMessage() {}

func (x *DecodeRawPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRawPacketsRequest.ProtoReflect.Descriptor instead.
func (*DecodeRawPacketsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{0}
}

func (x *DecodeRawPacketsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DecodeRawPacketsRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *DecodeRawPacketsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DecodeRawPacketsRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *DecodeRawPacketsRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *DecodeRawPacketsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DecodeRawPacketsRequest) GetClearExisting() bool {
	if x != nil {
		return x.ClearExisting
	}
	return false
}

// DecodeRawPacketsResponse 离线解码结果统计。
type DecodeRawPacketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRaw      int64                  `protobuf:"varint,1,opt,name=total_raw,json=totalRaw,proto3" json:"total_raw,omitempty"`             // 符合过滤条件的原始包总数
	Decoded       int64                  `protobuf:"varint,2,opt,name=decoded,proto3" json:"decoded,omitempty"`                               // 成功解码数
	DecodeErrors  int64                  `protobuf:"varint,3,opt,name=decode_errors,json=decodeErrors,proto3" json:"decode_errors,omitempty"` // 解码失败数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRawPacketsResponse) Reset() {
	*x = DecodeRawPacketsResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRawPacketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRawPacketsResponse) ProtoMessage() {}

func (x *DecodeRawPacketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRawPacketsResponse.ProtoReflect.Descriptor instead.
func (*DecodeRawPacketsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{1}
}

func (x *DecodeRawPacketsResponse) GetTotalRaw() int64 {
	if x != nil {
		return x.TotalRaw
	}
	return 0
}

func (x *DecodeRawPacketsResponse) GetDecoded() int64 {
	if x != nil {
		return x.Decoded
	}
	return 0
}

func (x *DecodeRawPacketsResponse) GetDecodeErrors() int64 {
	if x != nil {
		return x.DecodeErrors
	}
	return 0
}

// TestPluginRequest 插件测试请求（隐私安全：不回传原始包）。
type TestPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // 原始包来源会话（仅离线/stopped）
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`                               // 被测插件名（按名路由，可不同于会话原插件）
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                           // 可选过滤：协议
	Src           string                 `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`                                     // 可选过滤：源 ip:port
	Dst           string                 `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`                                     // 可选过滤：目的 ip:port
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`                                // 测试包上限，0=全部
	SampleLimit   int64                  `protobuf:"varint,7,opt,name=sample_limit,json=sampleLimit,proto3" json:"sample_limit,omitempty"` // 返回的解码事件采样上限（建议默认 50）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPluginRequest) Reset() {
	*x = TestPluginRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPluginRequest) ProtoMessage() {}

func (x *TestPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPluginRequest.ProtoReflect.Descriptor instead.
func (*TestPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{2}
}

func (x *TestPluginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TestPluginRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *TestPluginRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TestPluginRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *TestPluginRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *TestPluginRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TestPluginRequest) GetSampleLimit() int64 {
	if x != nil {
		return x.SampleLimit
	}
	return 0
}

// TestEventLite 采样解码事件（插件解出来的相关数据，不含原始字节）。
type TestEventLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SchemaId      string                 `protobuf:"bytes,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	DataJson      string                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // 拍平后的关键 data.* 字段 JSON（可能截断）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEventLite) Reset() {
	*x = TestEventLite{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEventLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEventLite) ProtoMessage() {}

func (x *TestEventLite) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEventLite.ProtoReflect.Descriptor instead.
func (*TestEventLite) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{3}
}

func (x *TestEventLite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestEventLite) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *TestEventLite) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TestEventLite) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *TestEventLite) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

// TestErrorLite 单个解码失败样例（仅含定位信息，不含原始字节）。
type TestErrorLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawPacketId   string                 `protobuf:"bytes,1,opt,name=raw_packet_id,json=rawPacketId,proto3" json:"raw_packet_id,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestErrorLite) Reset() {
	*x = TestErrorLite{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestErrorLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestErrorLite) ProtoMessage() {}

func (x *TestErrorLite) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestErrorLite.ProtoReflect.Descriptor instead.
func (*TestErrorLite) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{4}
}

func (x *TestErrorLite) GetRawPacketId() string {
	if x != nil {
		return x.RawPacketId
	}
	return ""
}

func (x *TestErrorLite) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *TestErrorLite) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *TestErrorLite) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TestPluginResponse 插件测试结果：计数 + 类型分布 + 采样事件 + 错误样例。
type TestPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRaw      int64                  `protobuf:"varint,1,opt,name=total_raw,json=totalRaw,proto3" json:"total_raw,omitempty"`
	Decoded       int64                  `protobuf:"varint,2,opt,name=decoded,proto3" json:"decoded,omitempty"`
	DecodeErrors  int64                  `protobuf:"varint,3,opt,name=decode_errors,json=decodeErrors,proto3" json:"decode_errors,omitempty"`
	TypeHistogram map[string]int64       `protobuf:"bytes,4,rep,name=type_histogram,json=typeHistogram,proto3" json:"type_histogram,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 事件类型 → 计数（全量）
	SampleEvents  []*TestEventLite       `protobuf:"bytes,5,rep,name=sample_events,json=sampleEvents,proto3" json:"sample_events,omitempty"`
	ErrorSamples  []*TestErrorLite       `protobuf:"bytes,6,rep,name=error_samples,json=errorSamples,proto3" json:"error_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPluginResponse) Reset() {
	*x = TestPluginResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPluginResponse) ProtoMessage() {}

func (x *TestPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPluginResponse.ProtoReflect.Descriptor instead.
func (*TestPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{5}
}

func (x *TestPluginResponse) GetTotalRaw() int64 {
	if x != nil {
		return x.TotalRaw
	}
	return 0
}

func (x *TestPluginResponse) GetDecoded() int64 {
	if x != nil {
		return x.Decoded
	}
	return 0
}

func (x *TestPluginResponse) GetDecodeErrors() int64 {
	if x != nil {
		return x.DecodeErrors
	}
	return 0
}

func (x *TestPluginResponse) GetTypeHistogram() map[string]int64 {
	if x != nil {
		return x.TypeHistogram
	}
	return nil
}

func (x *TestPluginResponse) GetSampleEvents() []*TestEventLite {
	if x != nil {
		return x.SampleEvents
	}
	return nil
}

func (x *TestPluginResponse) GetErrorSamples() []*TestErrorLite {
	if x != nil {
		return x.ErrorSamples
	}
	return nil
}

// VerifyRequest 插件验证请求（契约+质量校验）。参数与 TestPlugin 同源：
// 指定会话 + 插件，可选 protocol/src/dst/limit 过滤。
type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Src           string                 `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = 全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VerifyRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *VerifyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *VerifyRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *VerifyRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *VerifyRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// VerifyViolation 单条契约违规（源自 SDK contract checker，带 rule_id）。
type VerifyViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Statement     string                 `protobuf:"bytes,4,opt,name=statement,proto3" json:"statement,omitempty"`
	DocRef        string                 `protobuf:"bytes,5,opt,name=doc_ref,json=docRef,proto3" json:"doc_ref,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Sample        string                 `protobuf:"bytes,7,opt,name=sample,proto3" json:"sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyViolation) Reset() {
	*x = VerifyViolation{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyViolation) ProtoMessage() {}

func (x *VerifyViolation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyViolation.ProtoReflect.Descriptor instead.
func (*VerifyViolation) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyViolation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *VerifyViolation) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *VerifyViolation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *VerifyViolation) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *VerifyViolation) GetDocRef() string {
	if x != nil {
		return x.DocRef
	}
	return ""
}

func (x *VerifyViolation) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VerifyViolation) GetSample() string {
	if x != nil {
		return x.Sample
	}
	return ""
}

// VerifyQuality gta 侧语料级统计（与 plugin.explain 共享判据）。
type VerifyQuality struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalInputs          int64                  `protobuf:"varint,1,opt,name=total_inputs,json=totalInputs,proto3" json:"total_inputs,omitempty"`
	UnknownInputs        int64                  `protobuf:"varint,2,opt,name=unknown_inputs,json=unknownInputs,proto3" json:"unknown_inputs,omitempty"`
	UnknownRatio         float64                `protobuf:"fixed64,3,opt,name=unknown_ratio,json=unknownRatio,proto3" json:"unknown_ratio,omitempty"`
	CorrelatedInputs     int64                  `protobuf:"varint,4,opt,name=correlated_inputs,json=correlatedInputs,proto3" json:"correlated_inputs,omitempty"`
	LongPacketErrors     int64                  `protobuf:"varint,5,opt,name=long_packet_errors,json=longPacketErrors,proto3" json:"long_packet_errors,omitempty"`
	EntropyEstimate      float64                `protobuf:"fixed64,6,opt,name=entropy_estimate,json=entropyEstimate,proto3" json:"entropy_estimate,omitempty"`
	SchemaVersionedRatio float64                `protobuf:"fixed64,7,opt,name=schema_versioned_ratio,json=schemaVersionedRatio,proto3" json:"schema_versioned_ratio,omitempty"`
	DecodeErrors         int64                  `protobuf:"varint,8,opt,name=decode_errors,json=decodeErrors,proto3" json:"decode_errors,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VerifyQuality) Reset() {
	*x = VerifyQuality{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQuality) ProtoMessage() {}

func (x *VerifyQuality) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQuality.ProtoReflect.Descriptor instead.
func (*VerifyQuality) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyQuality) GetTotalInputs() int64 {
	if x != nil {
		return x.TotalInputs
	}
	return 0
}

func (x *VerifyQuality) GetUnknownInputs() int64 {
	if x != nil {
		return x.UnknownInputs
	}
	return 0
}

func (x *VerifyQuality) GetUnknownRatio() float64 {
	if x != nil {
		return x.UnknownRatio
	}
	return 0
}

func (x *VerifyQuality) GetCorrelatedInputs() int64 {
	if x != nil {
		return x.CorrelatedInputs
	}
	return 0
}

func (x *VerifyQuality) GetLongPacketErrors() int64 {
	if x != nil {
		return x.LongPacketErrors
	}
	return 0
}

func (x *VerifyQuality) GetEntropyEstimate() float64 {
	if x != nil {
		return x.EntropyEstimate
	}
	return 0
}

func (x *VerifyQuality) GetSchemaVersionedRatio() float64 {
	if x != nil {
		return x.SchemaVersionedRatio
	}
	return 0
}

func (x *VerifyQuality) GetDecodeErrors() int64 {
	if x != nil {
		return x.DecodeErrors
	}
	return 0
}

// VerifyResponse 验证结论：violations + quality + verdict，外加溯源字段。
type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"` // pass | warn | fail
	Violations    []*VerifyViolation     `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	Quality       *VerifyQuality         `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	VerifyRunId   string                 `protobuf:"bytes,4,opt,name=verify_run_id,json=verifyRunId,proto3" json:"verify_run_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AtUnix        int64                  `protobuf:"varint,6,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *VerifyResponse) GetViolations() []*VerifyViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *VerifyResponse) GetQuality() *VerifyQuality {
	if x != nil {
		return x.Quality
	}
	return nil
}

func (x *VerifyResponse) GetVerifyRunId() string {
	if x != nil {
		return x.VerifyRunId
	}
	return ""
}

func (x *VerifyResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VerifyResponse) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

// SampleBytesRequest 取证取样请求。limit/max_bytes 为请求值，服务端封顶
// （20 包 / 64 字节），审计记真实返回量。
type SampleBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`                      // 仅用于审计 actor 标注
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                       // 请求包上限（服务端封顶 20）
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"` // 每包字节上限（服务端封顶 64）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleBytesRequest) Reset() {
	*x = SampleBytesRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleBytesRequest) ProtoMessage() {}

func (x *SampleBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleBytesRequest.ProtoReflect.Descriptor instead.
func (*SampleBytesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{10}
}

func (x *SampleBytesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SampleBytesRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *SampleBytesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SampleBytesRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// SampledPacket 单个原始包的事实快照（无解释）。
type SampledPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawPacketId   string                 `protobuf:"bytes,1,opt,name=raw_packet_id,json=rawPacketId,proto3" json:"raw_packet_id,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Hex           string                 `protobuf:"bytes,5,opt,name=hex,proto3" json:"hex,omitempty"`           // 截断后的 hexdump
	Entropy       float64                `protobuf:"fixed64,6,opt,name=entropy,proto3" json:"entropy,omitempty"` // 该包熵估计（bits/byte）
	FirstByte     int32                  `protobuf:"varint,7,opt,name=first_byte,json=firstByte,proto3" json:"first_byte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampledPacket) Reset() {
	*x = SampledPacket{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampledPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampledPacket) ProtoMessage() {}

func (x *SampledPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampledPacket.ProtoReflect.Descriptor instead.
func (*SampledPacket) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{11}
}

func (x *SampledPacket) GetRawPacketId() string {
	if x != nil {
		return x.RawPacketId
	}
	return ""
}

func (x *SampledPacket) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *SampledPacket) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *SampledPacket) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *SampledPacket) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

func (x *SampledPacket) GetEntropy() float64 {
	if x != nil {
		return x.Entropy
	}
	return 0
}

func (x *SampledPacket) GetFirstByte() int32 {
	if x != nil {
		return x.FirstByte
	}
	return 0
}

// SampleBytesResponse 取证事实 + 审计回执。
type SampleBytesResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestedPackets      int64                  `protobuf:"varint,2,opt,name=requested_packets,json=requestedPackets,proto3" json:"requested_packets,omitempty"`
	ReturnedPackets       int64                  `protobuf:"varint,3,opt,name=returned_packets,json=returnedPackets,proto3" json:"returned_packets,omitempty"`
	ReturnedBytes         int64                  `protobuf:"varint,4,opt,name=returned_bytes,json=returnedBytes,proto3" json:"returned_bytes,omitempty"`
	Truncated             bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Packets               []*SampledPacket       `protobuf:"bytes,6,rep,name=packets,proto3" json:"packets,omitempty"`
	LengthHistogram       map[int32]int64        `protobuf:"bytes,7,rep,name=length_histogram,json=lengthHistogram,proto3" json:"length_histogram,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                     // 长度桶 → 计数
	FirstByteDistribution map[int32]int64        `protobuf:"bytes,8,rep,name=first_byte_distribution,json=firstByteDistribution,proto3" json:"first_byte_distribution,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 首字节 → 计数
	MeanEntropy           float64                `protobuf:"fixed64,9,opt,name=mean_entropy,json=meanEntropy,proto3" json:"mean_entropy,omitempty"`                                                                                                           // 整体熵估计
	AuditId               int64                  `protobuf:"varint,10,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`                                                                                                                       // plugin_debug_access 行 id
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SampleBytesResponse) Reset() {
	*x = SampleBytesResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleBytesResponse) ProtoMessage() {}

func (x *SampleBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleBytesResponse.ProtoReflect.Descriptor instead.
func (*SampleBytesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{12}
}

func (x *SampleBytesResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SampleBytesResponse) GetRequestedPackets() int64 {
	if x != nil {
		return x.RequestedPackets
	}
	return 0
}

func (x *SampleBytesResponse) GetReturnedPackets() int64 {
	if x != nil {
		return x.ReturnedPackets
	}
	return 0
}

func (x *SampleBytesResponse) GetReturnedBytes() int64 {
	if x != nil {
		return x.ReturnedBytes
	}
	return 0
}

func (x *SampleBytesResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *SampleBytesResponse) GetPackets() []*SampledPacket {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *SampleBytesResponse) GetLengthHistogram() map[int32]int64 {
	if x != nil {
		return x.LengthHistogram
	}
	return nil
}

func (x *SampleBytesResponse) GetFirstByteDistribution() map[int32]int64 {
	if x != nil {
		return x.FirstByteDistribution
	}
	return nil
}

func (x *SampleBytesResponse) GetMeanEntropy() float64 {
	if x != nil {
		return x.MeanEntropy
	}
	return 0
}

func (x *SampleBytesResponse) GetAuditId() int64 {
	if x != nil {
		return x.AuditId
	}
	return 0
}

type PcapLiveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Bpf           string                 `protobuf:"bytes,2,opt,name=bpf,proto3" json:"bpf,omitempty"`
	SnapLen       int32                  `protobuf:"varint,3,opt,name=snap_len,json=snapLen,proto3" json:"snap_len,omitempty"`
	Promisc       bool                   `protobuf:"varint,4,opt,name=promisc,proto3" json:"promisc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PcapLiveConfig) Reset() {
	*x = PcapLiveConfig{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcapLiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcapLiveConfig) ProtoMessage() {}

func (x *PcapLiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcapLiveConfig.ProtoReflect.Descriptor instead.
func (*PcapLiveConfig) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{13}
}

func (x *PcapLiveConfig) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *PcapLiveConfig) GetBpf() string {
	if x != nil {
		return x.Bpf
	}
	return ""
}

func (x *PcapLiveConfig) GetSnapLen() int32 {
	if x != nil {
		return x.SnapLen
	}
	return 0
}

func (x *PcapLiveConfig) GetPromisc() bool {
	if x != nil {
		return x.Promisc
	}
	return false
}

type PcapFileConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PcapFileConfig) Reset() {
	*x = PcapFileConfig{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcapFileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcapFileConfig) ProtoMessage() {}

func (x *PcapFileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcapFileConfig.ProtoReflect.Descriptor instead.
func (*PcapFileConfig) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{14}
}

func (x *PcapFileConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StartCaptureRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plugin    string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Port      int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*StartCaptureRequest_Live
	//	*StartCaptureRequest_File
	Source        isStartCaptureRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCaptureRequest) Reset() {
	*x = StartCaptureRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCaptureRequest) ProtoMessage() {}

func (x *StartCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCaptureRequest.ProtoReflect.Descriptor instead.
func (*StartCaptureRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{15}
}

func (x *StartCaptureRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartCaptureRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *StartCaptureRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartCaptureRequest) GetSource() isStartCaptureRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StartCaptureRequest) GetLive() *PcapLiveConfig {
	if x != nil {
		if x, ok := x.Source.(*StartCaptureRequest_Live); ok {
			return x.Live
		}
	}
	return nil
}

func (x *StartCaptureRequest) GetFile() *PcapFileConfig {
	if x != nil {
		if x, ok := x.Source.(*StartCaptureRequest_File); ok {
			return x.File
		}
	}
	return nil
}

type isStartCaptureRequest_Source interface {
	isStartCaptureRequest_Source()
}

type StartCaptureRequest_Live struct {
	Live *PcapLiveConfig `protobuf:"bytes,4,opt,name=live,proto3,oneof"`
}

type StartCaptureRequest_File struct {
	File *PcapFileConfig `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

func (*StartCaptureRequest_Live) isStartCaptureRequest_Source() {}

func (*StartCaptureRequest_File) isStartCaptureRequest_Source() {}

type StartCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	DbPath        string                 `protobuf:"bytes,3,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCaptureResponse) Reset() {
	*x = StartCaptureResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCaptureResponse) ProtoMessage() {}

func (x *StartCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCaptureResponse.ProtoReflect.Descriptor instead.
func (*StartCaptureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{16}
}

func (x *StartCaptureResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartCaptureResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StartCaptureResponse) GetDbPath() string {
	if x != nil {
		return x.DbPath
	}
	return ""
}

type StopCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCaptureRequest) Reset() {
	*x = StopCaptureRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCaptureRequest) ProtoMessage() {}

func (x *StopCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCaptureRequest.ProtoReflect.Descriptor instead.
func (*StopCaptureRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{17}
}

func (x *StopCaptureRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	RawPackets    int64                  `protobuf:"varint,2,opt,name=raw_packets,json=rawPackets,proto3" json:"raw_packets,omitempty"`
	Events        int64                  `protobuf:"varint,3,opt,name=events,proto3" json:"events,omitempty"`
	Metrics       int64                  `protobuf:"varint,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	DecodeErrors  int64                  `protobuf:"varint,5,opt,name=decode_errors,json=decodeErrors,proto3" json:"decode_errors,omitempty"`
	DurationSec   float64                `protobuf:"fixed64,6,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCaptureResponse) Reset() {
	*x = StopCaptureResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCaptureResponse) ProtoMessage() {}

func (x *StopCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCaptureResponse.ProtoReflect.Descriptor instead.
func (*StopCaptureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{18}
}

func (x *StopCaptureResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StopCaptureResponse) GetRawPackets() int64 {
	if x != nil {
		return x.RawPackets
	}
	return 0
}

func (x *StopCaptureResponse) GetEvents() int64 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *StopCaptureResponse) GetMetrics() int64 {
	if x != nil {
		return x.Metrics
	}
	return 0
}

func (x *StopCaptureResponse) GetDecodeErrors() int64 {
	if x != nil {
		return x.DecodeErrors
	}
	return 0
}

func (x *StopCaptureResponse) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type GetCaptureStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptureStatusRequest) Reset() {
	*x = GetCaptureStatusRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptureStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptureStatusRequest) ProtoMessage() {}

func (x *GetCaptureStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptureStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCaptureStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{19}
}

func (x *GetCaptureStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetCaptureStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SourceName    string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	PacketsIn     uint64                 `protobuf:"varint,3,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	PacketsOut    uint64                 `protobuf:"varint,4,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	BytesIn       uint64                 `protobuf:"varint,5,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      uint64                 `protobuf:"varint,6,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Drops         uint64                 `protobuf:"varint,7,opt,name=drops,proto3" json:"drops,omitempty"`
	Errors        uint64                 `protobuf:"varint,8,opt,name=errors,proto3" json:"errors,omitempty"`
	Err           string                 `protobuf:"bytes,9,opt,name=err,proto3" json:"err,omitempty"`
	RawCount      int64                  `protobuf:"varint,10,opt,name=raw_count,json=rawCount,proto3" json:"raw_count,omitempty"`
	EventCount    int64                  `protobuf:"varint,11,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	MetricCount   int64                  `protobuf:"varint,12,opt,name=metric_count,json=metricCount,proto3" json:"metric_count,omitempty"`
	DecodeErrors  int64                  `protobuf:"varint,13,opt,name=decode_errors,json=decodeErrors,proto3" json:"decode_errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptureStatusResponse) Reset() {
	*x = GetCaptureStatusResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptureStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptureStatusResponse) ProtoMessage() {}

func (x *GetCaptureStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptureStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCaptureStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{20}
}

func (x *GetCaptureStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetCaptureStatusResponse) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *GetCaptureStatusResponse) GetPacketsIn() uint64 {
	if x != nil {
		return x.PacketsIn
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetPacketsOut() uint64 {
	if x != nil {
		return x.PacketsOut
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetDrops() uint64 {
	if x != nil {
		return x.Drops
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetErrors() uint64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *GetCaptureStatusResponse) GetRawCount() int64 {
	if x != nil {
		return x.RawCount
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetMetricCount() int64 {
	if x != nil {
		return x.MetricCount
	}
	return 0
}

func (x *GetCaptureStatusResponse) GetDecodeErrors() int64 {
	if x != nil {
		return x.DecodeErrors
	}
	return 0
}

type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{21}
}

type ListInterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesResponse) Reset() {
	*x = ListInterfacesResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponse) ProtoMessage() {}

func (x *ListInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesResponse.ProtoReflect.Descriptor instead.
func (*ListInterfacesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{22}
}

func (x *ListInterfacesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ListCaptureSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaptureSessionsRequest) Reset() {
	*x = ListCaptureSessionsRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaptureSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptureSessionsRequest) ProtoMessage() {}

func (x *ListCaptureSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptureSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListCaptureSessionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{23}
}

type ListCaptureSessionsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Sessions      []*CaptureSessionSummary `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaptureSessionsResponse) Reset() {
	*x = ListCaptureSessionsResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaptureSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptureSessionsResponse) ProtoMessage() {}

func (x *ListCaptureSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptureSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListCaptureSessionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{24}
}

func (x *ListCaptureSessionsResponse) GetSessions() []*CaptureSessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CaptureSessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SourceName    string                 `protobuf:"bytes,3,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Plugin        string                 `protobuf:"bytes,5,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Interface     string                 `protobuf:"bytes,6,opt,name=interface,proto3" json:"interface,omitempty"`
	PcapFile      string                 `protobuf:"bytes,7,opt,name=pcap_file,json=pcapFile,proto3" json:"pcap_file,omitempty"`
	StartedAtUnix int64                  `protobuf:"varint,8,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureSessionSummary) Reset() {
	*x = CaptureSessionSummary{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSessionSummary) ProtoMessage() {}

func (x *CaptureSessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSessionSummary.ProtoReflect.Descriptor instead.
func (*CaptureSessionSummary) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{25}
}

func (x *CaptureSessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CaptureSessionSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CaptureSessionSummary) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *CaptureSessionSummary) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CaptureSessionSummary) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *CaptureSessionSummary) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *CaptureSessionSummary) GetPcapFile() string {
	if x != nil {
		return x.PcapFile
	}
	return ""
}

func (x *CaptureSessionSummary) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{26}
}

// PluginSummary 插件注册摘要。
type PluginSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceId        string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol          string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Type              string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ApiVersion        string                 `protobuf:"bytes,5,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	SocketPath        string                 `protobuf:"bytes,6,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	Online            bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	LastHeartbeatUnix int64                  `protobuf:"varint,8,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginSummary) Reset() {
	*x = PluginSummary{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSummary) ProtoMessage() {}

func (x *PluginSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSummary.ProtoReflect.Descriptor instead.
func (*PluginSummary) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{27}
}

func (x *PluginSummary) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PluginSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginSummary) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PluginSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginSummary) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PluginSummary) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *PluginSummary) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PluginSummary) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginSummary       `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{28}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginSummary {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type GetPluginManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 插件名，留空返回所有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginManifestRequest) Reset() {
	*x = GetPluginManifestRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginManifestRequest) ProtoMessage() {}

func (x *GetPluginManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginManifestRequest.ProtoReflect.Descriptor instead.
func (*GetPluginManifestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{29}
}

func (x *GetPluginManifestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPluginManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"` // plugin.yaml 原始 bytes
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginManifestResponse) Reset() {
	*x = GetPluginManifestResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginManifestResponse) ProtoMessage() {}

func (x *GetPluginManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginManifestResponse.ProtoReflect.Descriptor instead.
func (*GetPluginManifestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{30}
}

func (x *GetPluginManifestResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *GetPluginManifestResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeregisterPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 优先使用 instance_id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 备选：按 name 注销所有匹配实例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPluginRequest) Reset() {
	*x = DeregisterPluginRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPluginRequest) ProtoMessage() {}

func (x *DeregisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPluginRequest.ProtoReflect.Descriptor instead.
func (*DeregisterPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{31}
}

func (x *DeregisterPluginRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterPluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeregisterPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPluginResponse) Reset() {
	*x = DeregisterPluginResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPluginResponse) ProtoMessage() {}

func (x *DeregisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPluginResponse.ProtoReflect.Descriptor instead.
func (*DeregisterPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{32}
}

func (x *DeregisterPluginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeregisterPluginResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterPluginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SetSessionPluginRequest 运行中热切换解码插件绑定请求。
// session_id 指定目标抓包会话；plugin 为新的解码插件名（按名精确路由）。
type SetSessionPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionPluginRequest) Reset() {
	*x = SetSessionPluginRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionPluginRequest) ProtoMessage() {}

func (x *SetSessionPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionPluginRequest.ProtoReflect.Descriptor instead.
func (*SetSessionPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{33}
}

func (x *SetSessionPluginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetSessionPluginRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

// SetSessionPluginResponse 热切换结果。
type SetSessionPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Plugin        string                 `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`   // 切换后的实际绑定插件名
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // 错误信息或状态说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionPluginResponse) Reset() {
	*x = SetSessionPluginResponse{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionPluginResponse) ProtoMessage() {}

func (x *SetSessionPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionPluginResponse.ProtoReflect.Descriptor instead.
func (*SetSessionPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{34}
}

func (x *SetSessionPluginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetSessionPluginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetSessionPluginResponse) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *SetSessionPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WatchPluginsRequest 订阅插件事件流（无参数）。
type WatchPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPluginsRequest) Reset() {
	*x = WatchPluginsRequest{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPluginsRequest) ProtoMessage() {}

func (x *WatchPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPluginsRequest.ProtoReflect.Descriptor instead.
func (*WatchPluginsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{35}
}

// PluginEvent 插件注册表状态变化通知。
// type 取值：register（新注册）| deregister（主动注销）| online（离线→在线）| offline（在线→离线）。
type PluginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                         // register | deregister | online | offline
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`           // 插件实例 ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                         // 插件名（manifest.name）
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`                                    // 事件后是否在线
	TimestampUnix int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // 事件发生时间（Unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEvent) Reset() {
	*x = PluginEvent{}
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEvent) ProtoMessage() {}

func (x *PluginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_internalipc_proto_internal_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEvent.ProtoReflect.Descriptor instead.
func (*PluginEvent) Descriptor() ([]byte, []int) {
	return file_pkg_internalipc_proto_internal_proto_rawDescGZIP(), []int{36}
}

func (x *PluginEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PluginEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginEvent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PluginEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_pkg_internalipc_proto_internal_proto protoreflect.FileDescriptor

const file_pkg_internalipc_proto_internal_proto_rawDesc = "" +
	"\n" +
	"$pkg/internalipc/proto/internal.proto\x12\x0fgta.internalipc\"\xcd\x01\n" +
	"\x17DecodeRawPacketsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x05 \x01(\tR\x03dst\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12%\n" +
	"\x0eclear_existing\x18\a \x01(\bR\rclearExisting\"v\n" +
	"\x18DecodeRawPacketsResponse\x12\x1b\n" +
	"\ttotal_raw\x18\x01 \x01(\x03R\btotalRaw\x12\x18\n" +
	"\adecoded\x18\x02 \x01(\x03R\adecoded\x12#\n" +
	"\rdecode_errors\x18\x03 \x01(\x03R\fdecodeErrors\"\xc3\x01\n" +
	"\x11TestPluginRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x05 \x01(\tR\x03dst\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12!\n" +
	"\fsample_limit\x18\a \x01(\x03R\vsampleLimit\"\x94\x01\n" +
	"\rTestEventLite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tschema_id\x18\x04 \x01(\tR\bschemaId\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\"m\n" +
	"\rTestErrorLite\x12\"\n" +
	"\rraw_packet_id\x18\x01 \x01(\tR\vrawPacketId\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9b\x03\n" +
	"\x12TestPluginResponse\x12\x1b\n" +
	"\ttotal_raw\x18\x01 \x01(\x03R\btotalRaw\x12\x18\n" +
	"\adecoded\x18\x02 \x01(\x03R\adecoded\x12#\n" +
	"\rdecode_errors\x18\x03 \x01(\x03R\fdecodeErrors\x12]\n" +
	"\x0etype_histogram\x18\x04 \x03(\v26.gta.internalipc.TestPluginResponse.TypeHistogramEntryR\rtypeHistogram\x12C\n" +
	"\rsample_events\x18\x05 \x03(\v2\x1e.gta.internalipc.TestEventLiteR\fsampleEvents\x12C\n" +
	"\rerror_samples\x18\x06 \x03(\v2\x1e.gta.internalipc.TestErrorLiteR\ferrorSamples\x1a@\n" +
	"\x12TypeHistogramEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x9c\x01\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x05 \x01(\tR\x03dst\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\"\xc1\x01\n" +
	"\x0fVerifyViolation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1c\n" +
	"\tstatement\x18\x04 \x01(\tR\tstatement\x12\x17\n" +
	"\adoc_ref\x18\x05 \x01(\tR\x06docRef\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x16\n" +
	"\x06sample\x18\a \x01(\tR\x06sample\"\xdf\x02\n" +
	"\rVerifyQuality\x12!\n" +
	"\ftotal_inputs\x18\x01 \x01(\x03R\vtotalInputs\x12%\n" +
	"\x0eunknown_inputs\x18\x02 \x01(\x03R\runknownInputs\x12#\n" +
	"\runknown_ratio\x18\x03 \x01(\x01R\funknownRatio\x12+\n" +
	"\x11correlated_inputs\x18\x04 \x01(\x03R\x10correlatedInputs\x12,\n" +
	"\x12long_packet_errors\x18\x05 \x01(\x03R\x10longPacketErrors\x12)\n" +
	"\x10entropy_estimate\x18\x06 \x01(\x01R\x0fentropyEstimate\x124\n" +
	"\x16schema_versioned_ratio\x18\a \x01(\x01R\x14schemaVersionedRatio\x12#\n" +
	"\rdecode_errors\x18\b \x01(\x03R\fdecodeErrors\"\x82\x02\n" +
	"\x0eVerifyResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12@\n" +
	"\n" +
	"violations\x18\x02 \x03(\v2 .gta.internalipc.VerifyViolationR\n" +
	"violations\x128\n" +
	"\aquality\x18\x03 \x01(\v2\x1e.gta.internalipc.VerifyQualityR\aquality\x12\"\n" +
	"\rverify_run_id\x18\x04 \x01(\tR\vverifyRunId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x17\n" +
	"\aat_unix\x18\x06 \x01(\x03R\x06atUnix\"~\n" +
	"\x12SampleBytesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\"\xba\x01\n" +
	"\rSampledPacket\x12\"\n" +
	"\rraw_packet_id\x18\x01 \x01(\tR\vrawPacketId\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\x12\x10\n" +
	"\x03hex\x18\x05 \x01(\tR\x03hex\x12\x18\n" +
	"\aentropy\x18\x06 \x01(\x01R\aentropy\x12\x1d\n" +
	"\n" +
	"first_byte\x18\a \x01(\x05R\tfirstByte\"\xb6\x05\n" +
	"\x13SampleBytesResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x11requested_packets\x18\x02 \x01(\x03R\x10requestedPackets\x12)\n" +
	"\x10returned_packets\x18\x03 \x01(\x03R\x0freturnedPackets\x12%\n" +
	"\x0ereturned_bytes\x18\x04 \x01(\x03R\rreturnedBytes\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x128\n" +
	"\apackets\x18\x06 \x03(\v2\x1e.gta.internalipc.SampledPacketR\apackets\x12d\n" +
	"\x10length_histogram\x18\a \x03(\v29.gta.internalipc.SampleBytesResponse.LengthHistogramEntryR\x0flengthHistogram\x12w\n" +
	"\x17first_byte_distribution\x18\b \x03(\v2?.gta.internalipc.SampleBytesResponse.FirstByteDistributionEntryR\x15firstByteDistribution\x12!\n" +
	"\fmean_entropy\x18\t \x01(\x01R\vmeanEntropy\x12\x19\n" +
	"\baudit_id\x18\n" +
	" \x01(\x03R\aauditId\x1aB\n" +
	"\x14LengthHistogramEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aH\n" +
	"\x1aFirstByteDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"o\n" +
	"\x0ePcapLiveConfig\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x10\n" +
	"\x03bpf\x18\x02 \x01(\tR\x03bpf\x12\x19\n" +
	"\bsnap_len\x18\x03 \x01(\x05R\asnapLen\x12\x18\n" +
	"\apromisc\x18\x04 \x01(\bR\apromisc\"$\n" +
	"\x0ePcapFileConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xd8\x01\n" +
	"\x13StartCaptureRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x125\n" +
	"\x04live\x18\x04 \x01(\v2\x1f.gta.internalipc.PcapLiveConfigH\x00R\x04live\x125\n" +
	"\x04file\x18\x05 \x01(\v2\x1f.gta.internalipc.PcapFileConfigH\x00R\x04fileB\b\n" +
	"\x06source\"d\n" +
	"\x14StartCaptureResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x17\n" +
	"\adb_path\x18\x03 \x01(\tR\x06dbPath\"3\n" +
	"\x12StopCaptureRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc6\x01\n" +
	"\x13StopCaptureResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1f\n" +
	"\vraw_packets\x18\x02 \x01(\x03R\n" +
	"rawPackets\x12\x16\n" +
	"\x06events\x18\x03 \x01(\x03R\x06events\x12\x18\n" +
	"\ametrics\x18\x04 \x01(\x03R\ametrics\x12#\n" +
	"\rdecode_errors\x18\x05 \x01(\x03R\fdecodeErrors\x12!\n" +
	"\fduration_sec\x18\x06 \x01(\x01R\vdurationSec\"8\n" +
	"\x17GetCaptureStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x8f\x03\n" +
	"\x18GetCaptureStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12\x1d\n" +
	"\n" +
	"packets_in\x18\x03 \x01(\x04R\tpacketsIn\x12\x1f\n" +
	"\vpackets_out\x18\x04 \x01(\x04R\n" +
	"packetsOut\x12\x19\n" +
	"\bbytes_in\x18\x05 \x01(\x04R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x06 \x01(\x04R\bbytesOut\x12\x14\n" +
	"\x05drops\x18\a \x01(\x04R\x05drops\x12\x16\n" +
	"\x06errors\x18\b \x01(\x04R\x06errors\x12\x10\n" +
	"\x03err\x18\t \x01(\tR\x03err\x12\x1b\n" +
	"\traw_count\x18\n" +
	" \x01(\x03R\brawCount\x12\x1f\n" +
	"\vevent_count\x18\v \x01(\x03R\n" +
	"eventCount\x12!\n" +
	"\fmetric_count\x18\f \x01(\x03R\vmetricCount\x12#\n" +
	"\rdecode_errors\x18\r \x01(\x03R\fdecodeErrors\"\x17\n" +
	"\x15ListInterfacesRequest\".\n" +
	"\x16ListInterfacesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x1c\n" +
	"\x1aListCaptureSessionsRequest\"a\n" +
	"\x1bListCaptureSessionsResponse\x12B\n" +
	"\bsessions\x18\x01 \x03(\v2&.gta.internalipc.CaptureSessionSummaryR\bsessions\"\xfc\x01\n" +
	"\x15CaptureSessionSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vsource_name\x18\x03 \x01(\tR\n" +
	"sourceName\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06plugin\x18\x05 \x01(\tR\x06plugin\x12\x1c\n" +
	"\tinterface\x18\x06 \x01(\tR\tinterface\x12\x1b\n" +
	"\tpcap_file\x18\a \x01(\tR\bpcapFile\x12&\n" +
	"\x0fstarted_at_unix\x18\b \x01(\x03R\rstartedAtUnix\"\x14\n" +
	"\x12ListPluginsRequest\"\xfe\x01\n" +
	"\rPluginSummary\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1f\n" +
	"\vapi_version\x18\x05 \x01(\tR\n" +
	"apiVersion\x12\x1f\n" +
	"\vsocket_path\x18\x06 \x01(\tR\n" +
	"socketPath\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\x12.\n" +
	"\x13last_heartbeat_unix\x18\b \x01(\x03R\x11lastHeartbeatUnix\"O\n" +
	"\x13ListPluginsResponse\x128\n" +
	"\aplugins\x18\x01 \x03(\v2\x1e.gta.internalipc.PluginSummaryR\aplugins\".\n" +
	"\x18GetPluginManifestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x19GetPluginManifestResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"N\n" +
	"\x17DeregisterPluginRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"_\n" +
	"\x18DeregisterPluginResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"P\n" +
	"\x17SetSessionPluginRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\"{\n" +
	"\x18SetSessionPluginResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06plugin\x18\x03 \x01(\tR\x06plugin\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x15\n" +
	"\x13WatchPluginsRequest\"\x95\x01\n" +
	"\vPluginEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix2\xd8\n" +
	"\n" +
	"\x0eCaptureControl\x12[\n" +
	"\fStartCapture\x12$.gta.internalipc.StartCaptureRequest\x1a%.gta.internalipc.StartCaptureResponse\x12X\n" +
	"\vStopCapture\x12#.gta.internalipc.StopCaptureRequest\x1a$.gta.internalipc.StopCaptureResponse\x12g\n" +
	"\x10GetCaptureStatus\x12(.gta.internalipc.GetCaptureStatusRequest\x1a).gta.internalipc.GetCaptureStatusResponse\x12p\n" +
	"\x13ListCaptureSessions\x12+.gta.internalipc.ListCaptureSessionsRequest\x1a,.gta.internalipc.ListCaptureSessionsResponse\x12a\n" +
	"\x0eListInterfaces\x12&.gta.internalipc.ListInterfacesRequest\x1a'.gta.internalipc.ListInterfacesResponse\x12g\n" +
	"\x10DecodeRawPackets\x12(.gta.internalipc.DecodeRawPacketsRequest\x1a).gta.internalipc.DecodeRawPacketsResponse\x12X\n" +
	"\vListPlugins\x12#.gta.internalipc.ListPluginsRequest\x1a$.gta.internalipc.ListPluginsResponse\x12j\n" +
	"\x11GetPluginManifest\x12).gta.internalipc.GetPluginManifestRequest\x1a*.gta.internalipc.GetPluginManifestResponse\x12g\n" +
	"\x10DeregisterPlugin\x12(.gta.internalipc.DeregisterPluginRequest\x1a).gta.internalipc.DeregisterPluginResponse\x12g\n" +
	"\x10SetSessionPlugin\x12(.gta.internalipc.SetSessionPluginRequest\x1a).gta.internalipc.SetSessionPluginResponse\x12T\n" +
	"\fWatchPlugins\x12$.gta.internalipc.WatchPluginsRequest\x1a\x1c.gta.internalipc.PluginEvent0\x01\x12U\n" +
	"\n" +
	"TestPlugin\x12\".gta.internalipc.TestPluginRequest\x1a#.gta.internalipc.TestPluginResponse\x12I\n" +
	"\x06Verify\x12\x1e.gta.internalipc.VerifyRequest\x1a\x1f.gta.internalipc.VerifyResponse\x12X\n" +
	"\vSampleBytes\x12#.gta.internalipc.SampleBytesRequest\x1a$.gta.internalipc.SampleBytesResponseB\x1bZ\x19gta/pkg/internalipc/protob\x06proto3"

var (
	file_pkg_internalipc_proto_internal_proto_rawDescOnce sync.Once
	file_pkg_internalipc_proto_internal_proto_rawDescData []byte
)

func file_pkg_internalipc_proto_internal_proto_rawDescGZIP() []byte {
	file_pkg_internalipc_proto_internal_proto_rawDescOnce.Do(func() {
		file_pkg_internalipc_proto_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_internalipc_proto_internal_proto_rawDesc), len(file_pkg_internalipc_proto_internal_proto_rawDesc)))
	})
	return file_pkg_internalipc_proto_internal_proto_rawDescData
}

var file_pkg_internalipc_proto_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_pkg_internalipc_proto_internal_proto_goTypes = []any{
	(*DecodeRawPacketsRequest)(nil),     // 0: gta.internalipc.DecodeRawPacketsRequest
	(*DecodeRawPacketsResponse)(nil),    // 1: gta.internalipc.DecodeRawPacketsResponse
	(*TestPluginRequest)(nil),           // 2: gta.internalipc.TestPluginRequest
	(*TestEventLite)(nil),               // 3: gta.internalipc.TestEventLite
	(*TestErrorLite)(nil),               // 4: gta.internalipc.TestErrorLite
	(*TestPluginResponse)(nil),          // 5: gta.internalipc.TestPluginResponse
	(*VerifyRequest)(nil),               // 6: gta.internalipc.VerifyRequest
	(*VerifyViolation)(nil),             // 7: gta.internalipc.VerifyViolation
	(*VerifyQuality)(nil),               // 8: gta.internalipc.VerifyQuality
	(*VerifyResponse)(nil),              // 9: gta.internalipc.VerifyResponse
	(*SampleBytesRequest)(nil),          // 10: gta.internalipc.SampleBytesRequest
	(*SampledPacket)(nil),               // 11: gta.internalipc.SampledPacket
	(*SampleBytesResponse)(nil),         // 12: gta.internalipc.SampleBytesResponse
	(*PcapLiveConfig)(nil),              // 13: gta.internalipc.PcapLiveConfig
	(*PcapFileConfig)(nil),              // 14: gta.internalipc.PcapFileConfig
	(*StartCaptureRequest)(nil),         // 15: gta.internalipc.StartCaptureRequest
	(*StartCaptureResponse)(nil),        // 16: gta.internalipc.StartCaptureResponse
	(*StopCaptureRequest)(nil),          // 17: gta.internalipc.StopCaptureRequest
	(*StopCaptureResponse)(nil),         // 18: gta.internalipc.StopCaptureResponse
	(*GetCaptureStatusRequest)(nil),     // 19: gta.internalipc.GetCaptureStatusRequest
	(*GetCaptureStatusResponse)(nil),    // 20: gta.internalipc.GetCaptureStatusResponse
	(*ListInterfacesRequest)(nil),       // 21: gta.internalipc.ListInterfacesRequest
	(*ListInterfacesResponse)(nil),      // 22: gta.internalipc.ListInterfacesResponse
	(*ListCaptureSessionsRequest)(nil),  // 23: gta.internalipc.ListCaptureSessionsRequest
	(*ListCaptureSessionsResponse)(nil), // 24: gta.internalipc.ListCaptureSessionsResponse
	(*CaptureSessionSummary)(nil),       // 25: gta.internalipc.CaptureSessionSummary
	(*ListPluginsRequest)(nil),          // 26: gta.internalipc.ListPluginsRequest
	(*PluginSummary)(nil),               // 27: gta.internalipc.PluginSummary
	(*ListPluginsResponse)(nil),         // 28: gta.internalipc.ListPluginsResponse
	(*GetPluginManifestRequest)(nil),    // 29: gta.internalipc.GetPluginManifestRequest
	(*GetPluginManifestResponse)(nil),   // 30: gta.internalipc.GetPluginManifestResponse
	(*DeregisterPluginRequest)(nil),     // 31: gta.internalipc.DeregisterPluginRequest
	(*DeregisterPluginResponse)(nil),    // 32: gta.internalipc.DeregisterPluginResponse
	(*SetSessionPluginRequest)(nil),     // 33: gta.internalipc.SetSessionPluginRequest
	(*SetSessionPluginResponse)(nil),    // 34: gta.internalipc.SetSessionPluginResponse
	(*WatchPluginsRequest)(nil),         // 35: gta.internalipc.WatchPluginsRequest
	(*PluginEvent)(nil),                 // 36: gta.internalipc.PluginEvent
	nil,                                 // 37: gta.internalipc.TestPluginResponse.TypeHistogramEntry
	nil,                                 // 38: gta.internalipc.SampleBytesResponse.LengthHistogramEntry
	nil,                                 // 39: gta.internalipc.SampleBytesResponse.FirstByteDistributionEntry
}
var file_pkg_internalipc_proto_internal_proto_depIdxs = []int32{
	37, // 0: gta.internalipc.TestPluginResponse.type_histogram:type_name -> gta.internalipc.TestPluginResponse.TypeHistogramEntry
	3,  // 1: gta.internalipc.TestPluginResponse.sample_events:type_name -> gta.internalipc.TestEventLite
	4,  // 2: gta.internalipc.TestPluginResponse.error_samples:type_name -> gta.internalipc.TestErrorLite
	7,  // 3: gta.internalipc.VerifyResponse.violations:type_name -> gta.internalipc.VerifyViolation
	8,  // 4: gta.internalipc.VerifyResponse.quality:type_name -> gta.internalipc.VerifyQuality
	11, // 5: gta.internalipc.SampleBytesResponse.packets:type_name -> gta.internalipc.SampledPacket
	38, // 6: gta.internalipc.SampleBytesResponse.length_histogram:type_name -> gta.internalipc.SampleBytesResponse.LengthHistogramEntry
	39, // 7: gta.internalipc.SampleBytesResponse.first_byte_distribution:type_name -> gta.internalipc.SampleBytesResponse.FirstByteDistributionEntry
	13, // 8: gta.internalipc.StartCaptureRequest.live:type_name -> gta.internalipc.PcapLiveConfig
	14, // 9: gta.internalipc.StartCaptureRequest.file:type_name -> gta.internalipc.PcapFileConfig
	25, // 10: gta.internalipc.ListCaptureSessionsResponse.sessions:type_name -> gta.internalipc.CaptureSessionSummary
	27, // 11: gta.internalipc.ListPluginsResponse.plugins:type_name -> gta.internalipc.PluginSummary
	15, // 12: gta.internalipc.CaptureControl.StartCapture:input_type -> gta.internalipc.StartCaptureRequest
	17, // 13: gta.internalipc.CaptureControl.StopCapture:input_type -> gta.internalipc.StopCaptureRequest
	19, // 14: gta.internalipc.CaptureControl.GetCaptureStatus:input_type -> gta.internalipc.GetCaptureStatusRequest
	23, // 15: gta.internalipc.CaptureControl.ListCaptureSessions:input_type -> gta.internalipc.ListCaptureSessionsRequest
	21, // 16: gta.internalipc.CaptureControl.ListInterfaces:input_type -> gta.internalipc.ListInterfacesRequest
	0,  // 17: gta.internalipc.CaptureControl.DecodeRawPackets:input_type -> gta.internalipc.DecodeRawPacketsRequest
	26, // 18: gta.internalipc.CaptureControl.ListPlugins:input_type -> gta.internalipc.ListPluginsRequest
	29, // 19: gta.internalipc.CaptureControl.GetPluginManifest:input_type -> gta.internalipc.GetPluginManifestRequest
	31, // 20: gta.internalipc.CaptureControl.DeregisterPlugin:input_type -> gta.internalipc.DeregisterPluginRequest
	33, // 21: gta.internalipc.CaptureControl.SetSessionPlugin:input_type -> gta.internalipc.SetSessionPluginRequest
	35, // 22: gta.internalipc.CaptureControl.WatchPlugins:input_type -> gta.internalipc.WatchPluginsRequest
	2,  // 23: gta.internalipc.CaptureControl.TestPlugin:input_type -> gta.internalipc.TestPluginRequest
	6,  // 24: gta.internalipc.CaptureControl.Verify:input_type -> gta.internalipc.VerifyRequest
	10, // 25: gta.internalipc.CaptureControl.SampleBytes:input_type -> gta.internalipc.SampleBytesRequest
	16, // 26: gta.internalipc.CaptureControl.StartCapture:output_type -> gta.internalipc.StartCaptureResponse
	18, // 27: gta.internalipc.CaptureControl.StopCapture:output_type -> gta.internalipc.StopCaptureResponse
	20, // 28: gta.internalipc.CaptureControl.GetCaptureStatus:output_type -> gta.internalipc.GetCaptureStatusResponse
	24, // 29: gta.internalipc.CaptureControl.ListCaptureSessions:output_type -> gta.internalipc.ListCaptureSessionsResponse
	22, // 30: gta.internalipc.CaptureControl.ListInterfaces:output_type -> gta.internalipc.ListInterfacesResponse
	1,  // 31: gta.internalipc.CaptureControl.DecodeRawPackets:output_type -> gta.internalipc.DecodeRawPacketsResponse
	28, // 32: gta.internalipc.CaptureControl.ListPlugins:output_type -> gta.internalipc.ListPluginsResponse
	30, // 33: gta.internalipc.CaptureControl.GetPluginManifest:output_type -> gta.internalipc.GetPluginManifestResponse
	32, // 34: gta.internalipc.CaptureControl.DeregisterPlugin:output_type -> gta.internalipc.DeregisterPluginResponse
	34, // 35: gta.internalipc.CaptureControl.SetSessionPlugin:output_type -> gta.internalipc.SetSessionPluginResponse
	36, // 36: gta.internalipc.CaptureControl.WatchPlugins:output_type -> gta.internalipc.PluginEvent
	5,  // 37: gta.internalipc.CaptureControl.TestPlugin:output_type -> gta.internalipc.TestPluginResponse
	9,  // 38: gta.internalipc.CaptureControl.Verify:output_type -> gta.internalipc.VerifyResponse
	12, // 39: gta.internalipc.CaptureControl.SampleBytes:output_type -> gta.internalipc.SampleBytesResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_internalipc_proto_internal_proto_init() }
func file_pkg_internalipc_proto_internal_proto_init() {
	if File_pkg_internalipc_proto_internal_proto != nil {
		return
	}
	file_pkg_internalipc_proto_internal_proto_msgTypes[15].OneofWrappers = []any{
		(*StartCaptureRequest_Live)(nil),
		(*StartCaptureRequest_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_internalipc_proto_internal_proto_rawDesc), len(file_pkg_internalipc_proto_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_internalipc_proto_internal_proto_goTypes,
		DependencyIndexes: file_pkg_internalipc_proto_internal_proto_depIdxs,
		MessageInfos:      file_pkg_internalipc_proto_internal_proto_msgTypes,
	}.Build()
	File_pkg_internalipc_proto_internal_proto = out.File
	file_pkg_internalipc_proto_internal_proto_goTypes = nil
	file_pkg_internalipc_proto_internal_proto_depIdxs = nil
}
