// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: pkg/internalipc/proto/internal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaptureControl_StartCapture_FullMethodName        = "/gametrace.internalipc.CaptureControl/StartCapture"
	CaptureControl_StopCapture_FullMethodName         = "/gametrace.internalipc.CaptureControl/StopCapture"
	CaptureControl_GetCaptureStatus_FullMethodName    = "/gametrace.internalipc.CaptureControl/GetCaptureStatus"
	CaptureControl_ListCaptureSessions_FullMethodName = "/gametrace.internalipc.CaptureControl/ListCaptureSessions"
	CaptureControl_ListInterfaces_FullMethodName      = "/gametrace.internalipc.CaptureControl/ListInterfaces"
	CaptureControl_DecodeRawPackets_FullMethodName    = "/gametrace.internalipc.CaptureControl/DecodeRawPackets"
	CaptureControl_ListPlugins_FullMethodName         = "/gametrace.internalipc.CaptureControl/ListPlugins"
	CaptureControl_GetPluginManifest_FullMethodName   = "/gametrace.internalipc.CaptureControl/GetPluginManifest"
	CaptureControl_DeregisterPlugin_FullMethodName    = "/gametrace.internalipc.CaptureControl/DeregisterPlugin"
	CaptureControl_SetSessionPlugin_FullMethodName    = "/gametrace.internalipc.CaptureControl/SetSessionPlugin"
	CaptureControl_WatchPlugins_FullMethodName        = "/gametrace.internalipc.CaptureControl/WatchPlugins"
	CaptureControl_TestPlugin_FullMethodName          = "/gametrace.internalipc.CaptureControl/TestPlugin"
	CaptureControl_Verify_FullMethodName              = "/gametrace.internalipc.CaptureControl/Verify"
	CaptureControl_SampleBytes_FullMethodName         = "/gametrace.internalipc.CaptureControl/SampleBytes"
	CaptureControl_GetRegistryAddr_FullMethodName     = "/gametrace.internalipc.CaptureControl/GetRegistryAddr"
	CaptureControl_CreateProxyLease_FullMethodName    = "/gametrace.internalipc.CaptureControl/CreateProxyLease"
	CaptureControl_ListProxyLeases_FullMethodName     = "/gametrace.internalipc.CaptureControl/ListProxyLeases"
	CaptureControl_GetProxyLease_FullMethodName       = "/gametrace.internalipc.CaptureControl/GetProxyLease"
	CaptureControl_ReleaseProxyLease_FullMethodName   = "/gametrace.internalipc.CaptureControl/ReleaseProxyLease"
	CaptureControl_ListProbes_FullMethodName          = "/gametrace.internalipc.CaptureControl/ListProbes"
	CaptureControl_GetProbe_FullMethodName            = "/gametrace.internalipc.CaptureControl/GetProbe"
	CaptureControl_ProbeStartCapture_FullMethodName   = "/gametrace.internalipc.CaptureControl/ProbeStartCapture"
	CaptureControl_ProbeStopCapture_FullMethodName    = "/gametrace.internalipc.CaptureControl/ProbeStopCapture"
	CaptureControl_ProbeUpdateFilter_FullMethodName   = "/gametrace.internalipc.CaptureControl/ProbeUpdateFilter"
	CaptureControl_ProbeRetryCapture_FullMethodName   = "/gametrace.internalipc.CaptureControl/ProbeRetryCapture"
	CaptureControl_ProbeRename_FullMethodName         = "/gametrace.internalipc.CaptureControl/ProbeRename"
	CaptureControl_ProbeRevoke_FullMethodName         = "/gametrace.internalipc.CaptureControl/ProbeRevoke"
	CaptureControl_ProbeListArchive_FullMethodName    = "/gametrace.internalipc.CaptureControl/ProbeListArchive"
	CaptureControl_ProbeImportArchive_FullMethodName  = "/gametrace.internalipc.CaptureControl/ProbeImportArchive"
	CaptureControl_StartLeaseCapture_FullMethodName   = "/gametrace.internalipc.CaptureControl/StartLeaseCapture"
	CaptureControl_StopLeaseCapture_FullMethodName    = "/gametrace.internalipc.CaptureControl/StopLeaseCapture"
)

// CaptureControlClient is the client API for CaptureControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptureControl 由 gt-pipeline 进程提供，gt-mcp 作为 client 调用。
// 仅控制面 unary RPC，无 streaming。数据面走 SQLite。
type CaptureControlClient interface {
	// StartCapture 启动一次抓包会话。
	StartCapture(ctx context.Context, in *StartCaptureRequest, opts ...grpc.CallOption) (*StartCaptureResponse, error)
	// StopCapture 停止当前抓包会话。
	StopCapture(ctx context.Context, in *StopCaptureRequest, opts ...grpc.CallOption) (*StopCaptureResponse, error)
	// GetCaptureStatus 查询抓包状态与统计。
	GetCaptureStatus(ctx context.Context, in *GetCaptureStatusRequest, opts ...grpc.CallOption) (*GetCaptureStatusResponse, error)
	// ListCaptureSessions 列出当前活跃的抓包会话。
	ListCaptureSessions(ctx context.Context, in *ListCaptureSessionsRequest, opts ...grpc.CallOption) (*ListCaptureSessionsResponse, error)
	// ListInterfaces 列出可用网卡。
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	// DecodeRawPackets 用指定插件对离线会话的 raw_packets 批量解码，
	// 结果写入该 session 的 events 表。
	DecodeRawPackets(ctx context.Context, in *DecodeRawPacketsRequest, opts ...grpc.CallOption) (*DecodeRawPacketsResponse, error)
	// ListPlugins 列出当前已注册的插件摘要。
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// GetPluginManifest 获取指定插件的 manifest bytes（plugin.yaml 原始内容）。
	GetPluginManifest(ctx context.Context, in *GetPluginManifestRequest, opts ...grpc.CallOption) (*GetPluginManifestResponse, error)
	// DeregisterPlugin 注销指定插件（按 instance_id 或 name）。
	DeregisterPlugin(ctx context.Context, in *DeregisterPluginRequest, opts ...grpc.CallOption) (*DeregisterPluginResponse, error)
	// SetSessionPlugin 运行中热切换某抓包会话的解码插件绑定。
	// 切换后立即触发解码器重解析，无需停止再重启抓包。
	SetSessionPlugin(ctx context.Context, in *SetSessionPluginRequest, opts ...grpc.CallOption) (*SetSessionPluginResponse, error)
	// WatchPlugins 服务端流式推送插件注册表状态变化（register/deregister/online/offline）。
	// 用于前端即时刷新插件面板、以及抓包侧即时感知插件上下线，避免轮询延迟。
	WatchPlugins(ctx context.Context, in *WatchPluginsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PluginEvent], error)
	// TestPlugin 用指定插件对离线会话的 raw_packets 解码并采样返回，用于验证插件解码质量。
	// 原始包字节仅进程内使用，绝不回传前端；结果不落库（隔离测试，不污染会话真实解码数据）。
	// 该能力不暴露原始包，因此无需 --enable-raw-debug 门控。
	TestPlugin(ctx context.Context, in *TestPluginRequest, opts ...grpc.CallOption) (*TestPluginResponse, error)
	// Verify 用指定插件对离线会话的 raw_packets 解码并做契约+质量校验，
	// 产出 violations（引 SDK checker，带 rule_id）+ quality（gametrace 统计）+ verdict。
	// 仅统计不落库；validated 证明写入 Developer Plane 的 Tracker（跨平面）。
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// SampleBytes 读取会话原始包的前若干字节（事实：hexdump/长度直方图/首字节分布/熵），
	// 不解释，并在 plugin_debug_access 留审计。硬上限由服务端强制（20 包 / 64 字节）。
	SampleBytes(ctx context.Context, in *SampleBytesRequest, opts ...grpc.CallOption) (*SampleBytesResponse, error)
	// GetRegistryAddr 返回插件应连接注册中心地址（即 -registry-addr 的值，如 :9091）。
	// gt-mcp 与插件启动时需要此地址填入 GT_REGISTRY_ADDR；此前只能由人工从
	// 启动日志中获取。改为由 pipeline 通过本 RPC 直接暴露，避免插件「不知道该连哪里」。
	GetRegistryAddr(ctx context.Context, in *GetRegistryAddrRequest, opts ...grpc.CallOption) (*GetRegistryAddrResponse, error)
	// CreateProxyLease 为调用方创建一个代理抓包租约：独立 mobile 抓包会话 +
	// 独立 gt-singbox-agent 进程（各自独立端口与筛选配置），手机连 agent 的
	// listen 端口。会话停止时租约自动回收（杀 agent、释放端口）。
	CreateProxyLease(ctx context.Context, in *CreateProxyLeaseRequest, opts ...grpc.CallOption) (*CreateProxyLeaseResponse, error)
	// ListProxyLeases 列出调用方可见的租约（admin 全可见，同 ListPlugins 语义）。
	ListProxyLeases(ctx context.Context, in *ListProxyLeasesRequest, opts ...grpc.CallOption) (*ListProxyLeasesResponse, error)
	// GetProxyLease 查询单个租约状态快照（owner 校验，不匹配按不存在处理）。
	GetProxyLease(ctx context.Context, in *GetProxyLeaseRequest, opts ...grpc.CallOption) (*GetProxyLeaseResponse, error)
	// ReleaseProxyLease 释放租约：停会话、杀 agent、回收端口（幂等）。
	ReleaseProxyLease(ctx context.Context, in *ReleaseProxyLeaseRequest, opts ...grpc.CallOption) (*ReleaseProxyLeaseResponse, error)
	// StartLeaseCapture 在常驻租约上开一次新的抓包会话。
	//
	// ---- Probe 管理（探针注册/状态/控制全部在 pipeline 侧，gt-mcp 代理调用）----
	// 探针是个人资源：owner 校验在 pipeline 侧做 creator 轴判定（本人或 admin）。
	ListProbes(ctx context.Context, in *ListProbesRequest, opts ...grpc.CallOption) (*ListProbesResponse, error)
	GetProbe(ctx context.Context, in *GetProbeRequest, opts ...grpc.CallOption) (*GetProbeResponse, error)
	// ProbeStartCapture 选定探针建会话并下发 AssignCapture（建会话 + 指派一体）。
	ProbeStartCapture(ctx context.Context, in *ProbeStartCaptureRequest, opts ...grpc.CallOption) (*ProbeStartCaptureResponse, error)
	ProbeStopCapture(ctx context.Context, in *ProbeStopCaptureRequest, opts ...grpc.CallOption) (*ProbeStopCaptureResponse, error)
	// ProbeUpdateFilter 热更新抓包过滤（BPF 重编译，不中断抓包）。
	ProbeUpdateFilter(ctx context.Context, in *ProbeUpdateFilterRequest, opts ...grpc.CallOption) (*ProbeUpdateFilterResponse, error)
	// ProbeRetryCapture 让 failed 状态的探针重试上一次 assign。
	ProbeRetryCapture(ctx context.Context, in *ProbeRetryCaptureRequest, opts ...grpc.CallOption) (*ProbeRetryCaptureResponse, error)
	ProbeRename(ctx context.Context, in *ProbeRenameRequest, opts ...grpc.CallOption) (*ProbeRenameResponse, error)
	// ProbeRevoke 作废 probe_token（探针下次启动需重新接入）。
	ProbeRevoke(ctx context.Context, in *ProbeRevokeRequest, opts ...grpc.CallOption) (*ProbeRevokeResponse, error)
	ProbeListArchive(ctx context.Context, in *ProbeListArchiveRequest, opts ...grpc.CallOption) (*ProbeListArchiveResponse, error)
	// ProbeImportArchive 把探针本地归档按时间窗回放导入为新会话（source=probe-archive）。
	ProbeImportArchive(ctx context.Context, in *ProbeImportArchiveRequest, opts ...grpc.CallOption) (*ProbeImportArchiveResponse, error)
	// 租约的代理出口（agent 进程 + 手机 CONNECT 端口）在整个租约生命周期内不变，
	// 本 RPC 只切换「抓不抓、抓到哪个会话」。手机侧无需重配代理、VPN 不中断。
	// 每次调用都是一个全新的会话（独立 session_id / 独立 SQLite / 独立 mobile
	// source），与上一次抓包完全隔离。租约已处于抓包中时返回错误（先 stop 再 start）。
	StartLeaseCapture(ctx context.Context, in *StartLeaseCaptureRequest, opts ...grpc.CallOption) (*StartLeaseCaptureResponse, error)
	// StopLeaseCapture 停止租约当前的抓包会话并回到 idle（出口继续保留）：
	// agent 立即停止上报，此后不再有原始包落盘与上报成本；手机连接不受影响。
	// 停止后可再次 StartLeaseCapture（新会话），支持反复开始/停止。
	StopLeaseCapture(ctx context.Context, in *StopLeaseCaptureRequest, opts ...grpc.CallOption) (*StopLeaseCaptureResponse, error)
}

type captureControlClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureControlClient(cc grpc.ClientConnInterface) CaptureControlClient {
	return &captureControlClient{cc}
}

func (c *captureControlClient) StartCapture(ctx context.Context, in *StartCaptureRequest, opts ...grpc.CallOption) (*StartCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_StartCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) StopCapture(ctx context.Context, in *StopCaptureRequest, opts ...grpc.CallOption) (*StopCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_StopCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetCaptureStatus(ctx context.Context, in *GetCaptureStatusRequest, opts ...grpc.CallOption) (*GetCaptureStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaptureStatusResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetCaptureStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListCaptureSessions(ctx context.Context, in *ListCaptureSessionsRequest, opts ...grpc.CallOption) (*ListCaptureSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCaptureSessionsResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListCaptureSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) DecodeRawPackets(ctx context.Context, in *DecodeRawPacketsRequest, opts ...grpc.CallOption) (*DecodeRawPacketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeRawPacketsResponse)
	err := c.cc.Invoke(ctx, CaptureControl_DecodeRawPackets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetPluginManifest(ctx context.Context, in *GetPluginManifestRequest, opts ...grpc.CallOption) (*GetPluginManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginManifestResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetPluginManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) DeregisterPlugin(ctx context.Context, in *DeregisterPluginRequest, opts ...grpc.CallOption) (*DeregisterPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterPluginResponse)
	err := c.cc.Invoke(ctx, CaptureControl_DeregisterPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) SetSessionPlugin(ctx context.Context, in *SetSessionPluginRequest, opts ...grpc.CallOption) (*SetSessionPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSessionPluginResponse)
	err := c.cc.Invoke(ctx, CaptureControl_SetSessionPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) WatchPlugins(ctx context.Context, in *WatchPluginsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PluginEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaptureControl_ServiceDesc.Streams[0], CaptureControl_WatchPlugins_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPluginsRequest, PluginEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureControl_WatchPluginsClient = grpc.ServerStreamingClient[PluginEvent]

func (c *captureControlClient) TestPlugin(ctx context.Context, in *TestPluginRequest, opts ...grpc.CallOption) (*TestPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestPluginResponse)
	err := c.cc.Invoke(ctx, CaptureControl_TestPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, CaptureControl_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) SampleBytes(ctx context.Context, in *SampleBytesRequest, opts ...grpc.CallOption) (*SampleBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleBytesResponse)
	err := c.cc.Invoke(ctx, CaptureControl_SampleBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetRegistryAddr(ctx context.Context, in *GetRegistryAddrRequest, opts ...grpc.CallOption) (*GetRegistryAddrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistryAddrResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetRegistryAddr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) CreateProxyLease(ctx context.Context, in *CreateProxyLeaseRequest, opts ...grpc.CallOption) (*CreateProxyLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProxyLeaseResponse)
	err := c.cc.Invoke(ctx, CaptureControl_CreateProxyLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListProxyLeases(ctx context.Context, in *ListProxyLeasesRequest, opts ...grpc.CallOption) (*ListProxyLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProxyLeasesResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListProxyLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetProxyLease(ctx context.Context, in *GetProxyLeaseRequest, opts ...grpc.CallOption) (*GetProxyLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProxyLeaseResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetProxyLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ReleaseProxyLease(ctx context.Context, in *ReleaseProxyLeaseRequest, opts ...grpc.CallOption) (*ReleaseProxyLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseProxyLeaseResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ReleaseProxyLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ListProbes(ctx context.Context, in *ListProbesRequest, opts ...grpc.CallOption) (*ListProbesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProbesResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ListProbes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) GetProbe(ctx context.Context, in *GetProbeRequest, opts ...grpc.CallOption) (*GetProbeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProbeResponse)
	err := c.cc.Invoke(ctx, CaptureControl_GetProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeStartCapture(ctx context.Context, in *ProbeStartCaptureRequest, opts ...grpc.CallOption) (*ProbeStartCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeStartCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeStartCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeStopCapture(ctx context.Context, in *ProbeStopCaptureRequest, opts ...grpc.CallOption) (*ProbeStopCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeStopCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeStopCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeUpdateFilter(ctx context.Context, in *ProbeUpdateFilterRequest, opts ...grpc.CallOption) (*ProbeUpdateFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeUpdateFilterResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeUpdateFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeRetryCapture(ctx context.Context, in *ProbeRetryCaptureRequest, opts ...grpc.CallOption) (*ProbeRetryCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeRetryCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeRetryCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeRename(ctx context.Context, in *ProbeRenameRequest, opts ...grpc.CallOption) (*ProbeRenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeRenameResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeRevoke(ctx context.Context, in *ProbeRevokeRequest, opts ...grpc.CallOption) (*ProbeRevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeRevokeResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeRevoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeListArchive(ctx context.Context, in *ProbeListArchiveRequest, opts ...grpc.CallOption) (*ProbeListArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeListArchiveResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeListArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) ProbeImportArchive(ctx context.Context, in *ProbeImportArchiveRequest, opts ...grpc.CallOption) (*ProbeImportArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeImportArchiveResponse)
	err := c.cc.Invoke(ctx, CaptureControl_ProbeImportArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) StartLeaseCapture(ctx context.Context, in *StartLeaseCaptureRequest, opts ...grpc.CallOption) (*StartLeaseCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLeaseCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_StartLeaseCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureControlClient) StopLeaseCapture(ctx context.Context, in *StopLeaseCaptureRequest, opts ...grpc.CallOption) (*StopLeaseCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopLeaseCaptureResponse)
	err := c.cc.Invoke(ctx, CaptureControl_StopLeaseCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureControlServer is the server API for CaptureControl service.
// All implementations must embed UnimplementedCaptureControlServer
// for forward compatibility.
//
// CaptureControl 由 gt-pipeline 进程提供，gt-mcp 作为 client 调用。
// 仅控制面 unary RPC，无 streaming。数据面走 SQLite。
type CaptureControlServer interface {
	// StartCapture 启动一次抓包会话。
	StartCapture(context.Context, *StartCaptureRequest) (*StartCaptureResponse, error)
	// StopCapture 停止当前抓包会话。
	StopCapture(context.Context, *StopCaptureRequest) (*StopCaptureResponse, error)
	// GetCaptureStatus 查询抓包状态与统计。
	GetCaptureStatus(context.Context, *GetCaptureStatusRequest) (*GetCaptureStatusResponse, error)
	// ListCaptureSessions 列出当前活跃的抓包会话。
	ListCaptureSessions(context.Context, *ListCaptureSessionsRequest) (*ListCaptureSessionsResponse, error)
	// ListInterfaces 列出可用网卡。
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	// DecodeRawPackets 用指定插件对离线会话的 raw_packets 批量解码，
	// 结果写入该 session 的 events 表。
	DecodeRawPackets(context.Context, *DecodeRawPacketsRequest) (*DecodeRawPacketsResponse, error)
	// ListPlugins 列出当前已注册的插件摘要。
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// GetPluginManifest 获取指定插件的 manifest bytes（plugin.yaml 原始内容）。
	GetPluginManifest(context.Context, *GetPluginManifestRequest) (*GetPluginManifestResponse, error)
	// DeregisterPlugin 注销指定插件（按 instance_id 或 name）。
	DeregisterPlugin(context.Context, *DeregisterPluginRequest) (*DeregisterPluginResponse, error)
	// SetSessionPlugin 运行中热切换某抓包会话的解码插件绑定。
	// 切换后立即触发解码器重解析，无需停止再重启抓包。
	SetSessionPlugin(context.Context, *SetSessionPluginRequest) (*SetSessionPluginResponse, error)
	// WatchPlugins 服务端流式推送插件注册表状态变化（register/deregister/online/offline）。
	// 用于前端即时刷新插件面板、以及抓包侧即时感知插件上下线，避免轮询延迟。
	WatchPlugins(*WatchPluginsRequest, grpc.ServerStreamingServer[PluginEvent]) error
	// TestPlugin 用指定插件对离线会话的 raw_packets 解码并采样返回，用于验证插件解码质量。
	// 原始包字节仅进程内使用，绝不回传前端；结果不落库（隔离测试，不污染会话真实解码数据）。
	// 该能力不暴露原始包，因此无需 --enable-raw-debug 门控。
	TestPlugin(context.Context, *TestPluginRequest) (*TestPluginResponse, error)
	// Verify 用指定插件对离线会话的 raw_packets 解码并做契约+质量校验，
	// 产出 violations（引 SDK checker，带 rule_id）+ quality（gametrace 统计）+ verdict。
	// 仅统计不落库；validated 证明写入 Developer Plane 的 Tracker（跨平面）。
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// SampleBytes 读取会话原始包的前若干字节（事实：hexdump/长度直方图/首字节分布/熵），
	// 不解释，并在 plugin_debug_access 留审计。硬上限由服务端强制（20 包 / 64 字节）。
	SampleBytes(context.Context, *SampleBytesRequest) (*SampleBytesResponse, error)
	// GetRegistryAddr 返回插件应连接注册中心地址（即 -registry-addr 的值，如 :9091）。
	// gt-mcp 与插件启动时需要此地址填入 GT_REGISTRY_ADDR；此前只能由人工从
	// 启动日志中获取。改为由 pipeline 通过本 RPC 直接暴露，避免插件「不知道该连哪里」。
	GetRegistryAddr(context.Context, *GetRegistryAddrRequest) (*GetRegistryAddrResponse, error)
	// CreateProxyLease 为调用方创建一个代理抓包租约：独立 mobile 抓包会话 +
	// 独立 gt-singbox-agent 进程（各自独立端口与筛选配置），手机连 agent 的
	// listen 端口。会话停止时租约自动回收（杀 agent、释放端口）。
	CreateProxyLease(context.Context, *CreateProxyLeaseRequest) (*CreateProxyLeaseResponse, error)
	// ListProxyLeases 列出调用方可见的租约（admin 全可见，同 ListPlugins 语义）。
	ListProxyLeases(context.Context, *ListProxyLeasesRequest) (*ListProxyLeasesResponse, error)
	// GetProxyLease 查询单个租约状态快照（owner 校验，不匹配按不存在处理）。
	GetProxyLease(context.Context, *GetProxyLeaseRequest) (*GetProxyLeaseResponse, error)
	// ReleaseProxyLease 释放租约：停会话、杀 agent、回收端口（幂等）。
	ReleaseProxyLease(context.Context, *ReleaseProxyLeaseRequest) (*ReleaseProxyLeaseResponse, error)
	// StartLeaseCapture 在常驻租约上开一次新的抓包会话。
	//
	// ---- Probe 管理（探针注册/状态/控制全部在 pipeline 侧，gt-mcp 代理调用）----
	// 探针是个人资源：owner 校验在 pipeline 侧做 creator 轴判定（本人或 admin）。
	ListProbes(context.Context, *ListProbesRequest) (*ListProbesResponse, error)
	GetProbe(context.Context, *GetProbeRequest) (*GetProbeResponse, error)
	// ProbeStartCapture 选定探针建会话并下发 AssignCapture（建会话 + 指派一体）。
	ProbeStartCapture(context.Context, *ProbeStartCaptureRequest) (*ProbeStartCaptureResponse, error)
	ProbeStopCapture(context.Context, *ProbeStopCaptureRequest) (*ProbeStopCaptureResponse, error)
	// ProbeUpdateFilter 热更新抓包过滤（BPF 重编译，不中断抓包）。
	ProbeUpdateFilter(context.Context, *ProbeUpdateFilterRequest) (*ProbeUpdateFilterResponse, error)
	// ProbeRetryCapture 让 failed 状态的探针重试上一次 assign。
	ProbeRetryCapture(context.Context, *ProbeRetryCaptureRequest) (*ProbeRetryCaptureResponse, error)
	ProbeRename(context.Context, *ProbeRenameRequest) (*ProbeRenameResponse, error)
	// ProbeRevoke 作废 probe_token（探针下次启动需重新接入）。
	ProbeRevoke(context.Context, *ProbeRevokeRequest) (*ProbeRevokeResponse, error)
	ProbeListArchive(context.Context, *ProbeListArchiveRequest) (*ProbeListArchiveResponse, error)
	// ProbeImportArchive 把探针本地归档按时间窗回放导入为新会话（source=probe-archive）。
	ProbeImportArchive(context.Context, *ProbeImportArchiveRequest) (*ProbeImportArchiveResponse, error)
	// 租约的代理出口（agent 进程 + 手机 CONNECT 端口）在整个租约生命周期内不变，
	// 本 RPC 只切换「抓不抓、抓到哪个会话」。手机侧无需重配代理、VPN 不中断。
	// 每次调用都是一个全新的会话（独立 session_id / 独立 SQLite / 独立 mobile
	// source），与上一次抓包完全隔离。租约已处于抓包中时返回错误（先 stop 再 start）。
	StartLeaseCapture(context.Context, *StartLeaseCaptureRequest) (*StartLeaseCaptureResponse, error)
	// StopLeaseCapture 停止租约当前的抓包会话并回到 idle（出口继续保留）：
	// agent 立即停止上报，此后不再有原始包落盘与上报成本；手机连接不受影响。
	// 停止后可再次 StartLeaseCapture（新会话），支持反复开始/停止。
	StopLeaseCapture(context.Context, *StopLeaseCaptureRequest) (*StopLeaseCaptureResponse, error)
	mustEmbedUnimplementedCaptureControlServer()
}

// UnimplementedCaptureControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureControlServer struct{}

func (UnimplementedCaptureControlServer) StartCapture(context.Context, *StartCaptureRequest) (*StartCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCapture not implemented")
}
func (UnimplementedCaptureControlServer) StopCapture(context.Context, *StopCaptureRequest) (*StopCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopCapture not implemented")
}
func (UnimplementedCaptureControlServer) GetCaptureStatus(context.Context, *GetCaptureStatusRequest) (*GetCaptureStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCaptureStatus not implemented")
}
func (UnimplementedCaptureControlServer) ListCaptureSessions(context.Context, *ListCaptureSessionsRequest) (*ListCaptureSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCaptureSessions not implemented")
}
func (UnimplementedCaptureControlServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedCaptureControlServer) DecodeRawPackets(context.Context, *DecodeRawPacketsRequest) (*DecodeRawPacketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeRawPackets not implemented")
}
func (UnimplementedCaptureControlServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedCaptureControlServer) GetPluginManifest(context.Context, *GetPluginManifestRequest) (*GetPluginManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginManifest not implemented")
}
func (UnimplementedCaptureControlServer) DeregisterPlugin(context.Context, *DeregisterPluginRequest) (*DeregisterPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterPlugin not implemented")
}
func (UnimplementedCaptureControlServer) SetSessionPlugin(context.Context, *SetSessionPluginRequest) (*SetSessionPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSessionPlugin not implemented")
}
func (UnimplementedCaptureControlServer) WatchPlugins(*WatchPluginsRequest, grpc.ServerStreamingServer[PluginEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPlugins not implemented")
}
func (UnimplementedCaptureControlServer) TestPlugin(context.Context, *TestPluginRequest) (*TestPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestPlugin not implemented")
}
func (UnimplementedCaptureControlServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedCaptureControlServer) SampleBytes(context.Context, *SampleBytesRequest) (*SampleBytesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SampleBytes not implemented")
}
func (UnimplementedCaptureControlServer) GetRegistryAddr(context.Context, *GetRegistryAddrRequest) (*GetRegistryAddrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistryAddr not implemented")
}
func (UnimplementedCaptureControlServer) CreateProxyLease(context.Context, *CreateProxyLeaseRequest) (*CreateProxyLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProxyLease not implemented")
}
func (UnimplementedCaptureControlServer) ListProxyLeases(context.Context, *ListProxyLeasesRequest) (*ListProxyLeasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProxyLeases not implemented")
}
func (UnimplementedCaptureControlServer) GetProxyLease(context.Context, *GetProxyLeaseRequest) (*GetProxyLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyLease not implemented")
}
func (UnimplementedCaptureControlServer) ReleaseProxyLease(context.Context, *ReleaseProxyLeaseRequest) (*ReleaseProxyLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseProxyLease not implemented")
}
func (UnimplementedCaptureControlServer) ListProbes(context.Context, *ListProbesRequest) (*ListProbesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProbes not implemented")
}
func (UnimplementedCaptureControlServer) GetProbe(context.Context, *GetProbeRequest) (*GetProbeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProbe not implemented")
}
func (UnimplementedCaptureControlServer) ProbeStartCapture(context.Context, *ProbeStartCaptureRequest) (*ProbeStartCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeStartCapture not implemented")
}
func (UnimplementedCaptureControlServer) ProbeStopCapture(context.Context, *ProbeStopCaptureRequest) (*ProbeStopCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeStopCapture not implemented")
}
func (UnimplementedCaptureControlServer) ProbeUpdateFilter(context.Context, *ProbeUpdateFilterRequest) (*ProbeUpdateFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeUpdateFilter not implemented")
}
func (UnimplementedCaptureControlServer) ProbeRetryCapture(context.Context, *ProbeRetryCaptureRequest) (*ProbeRetryCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeRetryCapture not implemented")
}
func (UnimplementedCaptureControlServer) ProbeRename(context.Context, *ProbeRenameRequest) (*ProbeRenameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeRename not implemented")
}
func (UnimplementedCaptureControlServer) ProbeRevoke(context.Context, *ProbeRevokeRequest) (*ProbeRevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeRevoke not implemented")
}
func (UnimplementedCaptureControlServer) ProbeListArchive(context.Context, *ProbeListArchiveRequest) (*ProbeListArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeListArchive not implemented")
}
func (UnimplementedCaptureControlServer) ProbeImportArchive(context.Context, *ProbeImportArchiveRequest) (*ProbeImportArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeImportArchive not implemented")
}
func (UnimplementedCaptureControlServer) StartLeaseCapture(context.Context, *StartLeaseCaptureRequest) (*StartLeaseCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLeaseCapture not implemented")
}
func (UnimplementedCaptureControlServer) StopLeaseCapture(context.Context, *StopLeaseCaptureRequest) (*StopLeaseCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopLeaseCapture not implemented")
}
func (UnimplementedCaptureControlServer) mustEmbedUnimplementedCaptureControlServer() {}
func (UnimplementedCaptureControlServer) testEmbeddedByValue()                        {}

// UnsafeCaptureControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureControlServer will
// result in compilation errors.
type UnsafeCaptureControlServer interface {
	mustEmbedUnimplementedCaptureControlServer()
}

func RegisterCaptureControlServer(s grpc.ServiceRegistrar, srv CaptureControlServer) {
	// If the following call panics, it indicates UnimplementedCaptureControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureControl_ServiceDesc, srv)
}

func _CaptureControl_StartCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).StartCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_StartCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).StartCapture(ctx, req.(*StartCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_StopCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).StopCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_StopCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).StopCapture(ctx, req.(*StopCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetCaptureStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptureStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetCaptureStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetCaptureStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetCaptureStatus(ctx, req.(*GetCaptureStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListCaptureSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCaptureSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListCaptureSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListCaptureSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListCaptureSessions(ctx, req.(*ListCaptureSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_DecodeRawPackets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRawPacketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).DecodeRawPackets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_DecodeRawPackets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).DecodeRawPackets(ctx, req.(*DecodeRawPacketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetPluginManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetPluginManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetPluginManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetPluginManifest(ctx, req.(*GetPluginManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_DeregisterPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).DeregisterPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_DeregisterPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).DeregisterPlugin(ctx, req.(*DeregisterPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_SetSessionPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSessionPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).SetSessionPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_SetSessionPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).SetSessionPlugin(ctx, req.(*SetSessionPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_WatchPlugins_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPluginsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaptureControlServer).WatchPlugins(m, &grpc.GenericServerStream[WatchPluginsRequest, PluginEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureControl_WatchPluginsServer = grpc.ServerStreamingServer[PluginEvent]

func _CaptureControl_TestPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).TestPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_TestPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).TestPlugin(ctx, req.(*TestPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_SampleBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).SampleBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_SampleBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).SampleBytes(ctx, req.(*SampleBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetRegistryAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistryAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetRegistryAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetRegistryAddr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetRegistryAddr(ctx, req.(*GetRegistryAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_CreateProxyLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProxyLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).CreateProxyLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_CreateProxyLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).CreateProxyLease(ctx, req.(*CreateProxyLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListProxyLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProxyLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListProxyLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListProxyLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListProxyLeases(ctx, req.(*ListProxyLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetProxyLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetProxyLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetProxyLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetProxyLease(ctx, req.(*GetProxyLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ReleaseProxyLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseProxyLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ReleaseProxyLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ReleaseProxyLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ReleaseProxyLease(ctx, req.(*ReleaseProxyLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ListProbes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProbesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ListProbes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ListProbes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ListProbes(ctx, req.(*ListProbesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_GetProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).GetProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_GetProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).GetProbe(ctx, req.(*GetProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeStartCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeStartCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeStartCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeStartCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeStartCapture(ctx, req.(*ProbeStartCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeStopCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeStopCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeStopCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeStopCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeStopCapture(ctx, req.(*ProbeStopCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeUpdateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeUpdateFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeUpdateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeUpdateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeUpdateFilter(ctx, req.(*ProbeUpdateFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeRetryCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRetryCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeRetryCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeRetryCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeRetryCapture(ctx, req.(*ProbeRetryCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeRename(ctx, req.(*ProbeRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeRevoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeRevoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeRevoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeRevoke(ctx, req.(*ProbeRevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeListArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeListArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeListArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeListArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeListArchive(ctx, req.(*ProbeListArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_ProbeImportArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeImportArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).ProbeImportArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_ProbeImportArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).ProbeImportArchive(ctx, req.(*ProbeImportArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_StartLeaseCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLeaseCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).StartLeaseCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_StartLeaseCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).StartLeaseCapture(ctx, req.(*StartLeaseCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureControl_StopLeaseCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLeaseCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureControlServer).StopLeaseCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureControl_StopLeaseCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureControlServer).StopLeaseCapture(ctx, req.(*StopLeaseCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptureControl_ServiceDesc is the grpc.ServiceDesc for CaptureControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gametrace.internalipc.CaptureControl",
	HandlerType: (*CaptureControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCapture",
			Handler:    _CaptureControl_StartCapture_Handler,
		},
		{
			MethodName: "StopCapture",
			Handler:    _CaptureControl_StopCapture_Handler,
		},
		{
			MethodName: "GetCaptureStatus",
			Handler:    _CaptureControl_GetCaptureStatus_Handler,
		},
		{
			MethodName: "ListCaptureSessions",
			Handler:    _CaptureControl_ListCaptureSessions_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _CaptureControl_ListInterfaces_Handler,
		},
		{
			MethodName: "DecodeRawPackets",
			Handler:    _CaptureControl_DecodeRawPackets_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _CaptureControl_ListPlugins_Handler,
		},
		{
			MethodName: "GetPluginManifest",
			Handler:    _CaptureControl_GetPluginManifest_Handler,
		},
		{
			MethodName: "DeregisterPlugin",
			Handler:    _CaptureControl_DeregisterPlugin_Handler,
		},
		{
			MethodName: "SetSessionPlugin",
			Handler:    _CaptureControl_SetSessionPlugin_Handler,
		},
		{
			MethodName: "TestPlugin",
			Handler:    _CaptureControl_TestPlugin_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _CaptureControl_Verify_Handler,
		},
		{
			MethodName: "SampleBytes",
			Handler:    _CaptureControl_SampleBytes_Handler,
		},
		{
			MethodName: "GetRegistryAddr",
			Handler:    _CaptureControl_GetRegistryAddr_Handler,
		},
		{
			MethodName: "CreateProxyLease",
			Handler:    _CaptureControl_CreateProxyLease_Handler,
		},
		{
			MethodName: "ListProxyLeases",
			Handler:    _CaptureControl_ListProxyLeases_Handler,
		},
		{
			MethodName: "GetProxyLease",
			Handler:    _CaptureControl_GetProxyLease_Handler,
		},
		{
			MethodName: "ReleaseProxyLease",
			Handler:    _CaptureControl_ReleaseProxyLease_Handler,
		},
		{
			MethodName: "ListProbes",
			Handler:    _CaptureControl_ListProbes_Handler,
		},
		{
			MethodName: "GetProbe",
			Handler:    _CaptureControl_GetProbe_Handler,
		},
		{
			MethodName: "ProbeStartCapture",
			Handler:    _CaptureControl_ProbeStartCapture_Handler,
		},
		{
			MethodName: "ProbeStopCapture",
			Handler:    _CaptureControl_ProbeStopCapture_Handler,
		},
		{
			MethodName: "ProbeUpdateFilter",
			Handler:    _CaptureControl_ProbeUpdateFilter_Handler,
		},
		{
			MethodName: "ProbeRetryCapture",
			Handler:    _CaptureControl_ProbeRetryCapture_Handler,
		},
		{
			MethodName: "ProbeRename",
			Handler:    _CaptureControl_ProbeRename_Handler,
		},
		{
			MethodName: "ProbeRevoke",
			Handler:    _CaptureControl_ProbeRevoke_Handler,
		},
		{
			MethodName: "ProbeListArchive",
			Handler:    _CaptureControl_ProbeListArchive_Handler,
		},
		{
			MethodName: "ProbeImportArchive",
			Handler:    _CaptureControl_ProbeImportArchive_Handler,
		},
		{
			MethodName: "StartLeaseCapture",
			Handler:    _CaptureControl_StartLeaseCapture_Handler,
		},
		{
			MethodName: "StopLeaseCapture",
			Handler:    _CaptureControl_StopLeaseCapture_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPlugins",
			Handler:       _CaptureControl_WatchPlugins_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/internalipc/proto/internal.proto",
}
