// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: pkg/capture/mobile/proto/mobile.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MobileCapture_Push_FullMethodName = "/gametrace.mobile.MobileCapture/Push"
)

// MobileCaptureClient is the client API for MobileCapture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MobileCapture 由 gt-pipeline 的 mobile capture source 提供（gRPC server）。
// gt-singbox-agent（sing-box 侧）作为 client 连接并推送连接级流量。
// 全连接共用一条流，靠 conn_id 区分；服务端按 (conn_id, direction) 归组，
// 但**不做**应用层分帧/重组——每个数据块原样透传为 packet，帧边界由解码插件判定。
type MobileCaptureClient interface {
	// Push 客户端流式推送 AgentEvent；结束返回汇总统计。
	// 一条连接的两个方向是独立的字节流，direction 用于区分。
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AgentEvent, PushResult], error)
}

type mobileCaptureClient struct {
	cc grpc.ClientConnInterface
}

func NewMobileCaptureClient(cc grpc.ClientConnInterface) MobileCaptureClient {
	return &mobileCaptureClient{cc}
}

func (c *mobileCaptureClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AgentEvent, PushResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MobileCapture_ServiceDesc.Streams[0], MobileCapture_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, PushResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MobileCapture_PushClient = grpc.ClientStreamingClient[AgentEvent, PushResult]

// MobileCaptureServer is the server API for MobileCapture service.
// All implementations must embed UnimplementedMobileCaptureServer
// for forward compatibility.
//
// MobileCapture 由 gt-pipeline 的 mobile capture source 提供（gRPC server）。
// gt-singbox-agent（sing-box 侧）作为 client 连接并推送连接级流量。
// 全连接共用一条流，靠 conn_id 区分；服务端按 (conn_id, direction) 归组，
// 但**不做**应用层分帧/重组——每个数据块原样透传为 packet，帧边界由解码插件判定。
type MobileCaptureServer interface {
	// Push 客户端流式推送 AgentEvent；结束返回汇总统计。
	// 一条连接的两个方向是独立的字节流，direction 用于区分。
	Push(grpc.ClientStreamingServer[AgentEvent, PushResult]) error
	mustEmbedUnimplementedMobileCaptureServer()
}

// UnimplementedMobileCaptureServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMobileCaptureServer struct{}

func (UnimplementedMobileCaptureServer) Push(grpc.ClientStreamingServer[AgentEvent, PushResult]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedMobileCaptureServer) mustEmbedUnimplementedMobileCaptureServer() {}
func (UnimplementedMobileCaptureServer) testEmbeddedByValue()                       {}

// UnsafeMobileCaptureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MobileCaptureServer will
// result in compilation errors.
type UnsafeMobileCaptureServer interface {
	mustEmbedUnimplementedMobileCaptureServer()
}

func RegisterMobileCaptureServer(s grpc.ServiceRegistrar, srv MobileCaptureServer) {
	// If the following call panics, it indicates UnimplementedMobileCaptureServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MobileCapture_ServiceDesc, srv)
}

func _MobileCapture_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MobileCaptureServer).Push(&grpc.GenericServerStream[AgentEvent, PushResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MobileCapture_PushServer = grpc.ClientStreamingServer[AgentEvent, PushResult]

// MobileCapture_ServiceDesc is the grpc.ServiceDesc for MobileCapture service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MobileCapture_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gametrace.mobile.MobileCapture",
	HandlerType: (*MobileCaptureServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _MobileCapture_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/capture/mobile/proto/mobile.proto",
}
