// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: pkg/capture/mobile/proto/mobile.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentEvent 是 agent → source 的单一事件流，按 conn_id 组织。
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`                       // 连接唯一标识（agent 生成，同一条连接保持一致）
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // 事件时间戳（Unix 秒）；0 表示使用接收时刻
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEvent_Open
	//	*AgentEvent_Data
	//	*AgentEvent_Close
	Event         isAgentEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_pkg_capture_mobile_proto_mobile_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEvent) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *AgentEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *AgentEvent) GetEvent() isAgentEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEvent) GetOpen() *ConnOpen {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *AgentEvent) GetData() *ConnData {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *AgentEvent) GetClose() *ConnClose {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isAgentEvent_Event interface {
	isAgentEvent_Event()
}

type AgentEvent_Open struct {
	Open *ConnOpen `protobuf:"bytes,10,opt,name=open,proto3,oneof"`
}

type AgentEvent_Data struct {
	Data *ConnData `protobuf:"bytes,11,opt,name=data,proto3,oneof"`
}

type AgentEvent_Close struct {
	Close *ConnClose `protobuf:"bytes,12,opt,name=close,proto3,oneof"`
}

func (*AgentEvent_Open) isAgentEvent_Event() {}

func (*AgentEvent_Data) isAgentEvent_Event() {}

func (*AgentEvent_Close) isAgentEvent_Event() {}

// ConnOpen 连接建立：携带连接元数据，应在同 conn_id 的 data 之前发送。
type ConnOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientAddr    string                 `protobuf:"bytes,1,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`    // "ip:port"，客户端（手机/本机侧）
	ServerAddr    string                 `protobuf:"bytes,2,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`    // "ip:port"，服务端（游戏服务器）
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`                            // "tcp" | "udp"
	App           string                 `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`                                    // 应用/包名（可选）
	Device        string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`                              // 设备标识（可选）
	ProcessName   string                 `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"` // 进程名（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnOpen) Reset() {
	*x = ConnOpen{}
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnOpen) ProtoMessage() {}

func (x *ConnOpen) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnOpen.ProtoReflect.Descriptor instead.
func (*ConnOpen) Descriptor() ([]byte, []int) {
	return file_pkg_capture_mobile_proto_mobile_proto_rawDescGZIP(), []int{1}
}

func (x *ConnOpen) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

func (x *ConnOpen) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *ConnOpen) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ConnOpen) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ConnOpen) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ConnOpen) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

// ConnData 连接数据块：一个方向的原始字节（一次 TCP read 或应用分块）。
type ConnData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"` // "request"(client→server) | "response"(server→client)
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnData) Reset() {
	*x = ConnData{}
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnData) ProtoMessage() {}

func (x *ConnData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnData.ProtoReflect.Descriptor instead.
func (*ConnData) Descriptor() ([]byte, []int) {
	return file_pkg_capture_mobile_proto_mobile_proto_rawDescGZIP(), []int{2}
}

func (x *ConnData) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ConnData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ConnClose 连接关闭：触发该连接缓冲区 flush。
type ConnClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // 关闭原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnClose) Reset() {
	*x = ConnClose{}
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnClose) ProtoMessage() {}

func (x *ConnClose) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnClose.ProtoReflect.Descriptor instead.
func (*ConnClose) Descriptor() ([]byte, []int) {
	return file_pkg_capture_mobile_proto_mobile_proto_rawDescGZIP(), []int{3}
}

func (x *ConnClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PushResult 推送汇总统计。
type PushResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   uint64                 `protobuf:"varint,1,opt,name=connections,proto3" json:"connections,omitempty"` // 已接收连接数
	Packets       uint64                 `protobuf:"varint,2,opt,name=packets,proto3" json:"packets,omitempty"`         // 已产出 Packet 数
	Bytes         uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`             // 已接收字节数
	Errors        uint64                 `protobuf:"varint,4,opt,name=errors,proto3" json:"errors,omitempty"`           // 错误/丢弃数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResult) Reset() {
	*x = PushResult{}
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResult) ProtoMessage() {}

func (x *PushResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_capture_mobile_proto_mobile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResult.ProtoReflect.Descriptor instead.
func (*PushResult) Descriptor() ([]byte, []int) {
	return file_pkg_capture_mobile_proto_mobile_proto_rawDescGZIP(), []int{4}
}

func (x *PushResult) GetConnections() uint64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *PushResult) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *PushResult) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *PushResult) GetErrors() uint64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

var File_pkg_capture_mobile_proto_mobile_proto protoreflect.FileDescriptor

const file_pkg_capture_mobile_proto_mobile_proto_rawDesc = "" +
	"\n" +
	"%pkg/capture/mobile/proto/mobile.proto\x12\n" +
	"gta.mobile\"\xdc\x01\n" +
	"\n" +
	"AgentEvent\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12*\n" +
	"\x04open\x18\n" +
	" \x01(\v2\x14.gta.mobile.ConnOpenH\x00R\x04open\x12*\n" +
	"\x04data\x18\v \x01(\v2\x14.gta.mobile.ConnDataH\x00R\x04data\x12-\n" +
	"\x05close\x18\f \x01(\v2\x15.gta.mobile.ConnCloseH\x00R\x05closeB\a\n" +
	"\x05event\"\xb3\x01\n" +
	"\bConnOpen\x12\x1f\n" +
	"\vclient_addr\x18\x01 \x01(\tR\n" +
	"clientAddr\x12\x1f\n" +
	"\vserver_addr\x18\x02 \x01(\tR\n" +
	"serverAddr\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x10\n" +
	"\x03app\x18\x04 \x01(\tR\x03app\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12!\n" +
	"\fprocess_name\x18\x06 \x01(\tR\vprocessName\"B\n" +
	"\bConnData\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"#\n" +
	"\tConnClose\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"v\n" +
	"\n" +
	"PushResult\x12 \n" +
	"\vconnections\x18\x01 \x01(\x04R\vconnections\x12\x18\n" +
	"\apackets\x18\x02 \x01(\x04R\apackets\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\x12\x16\n" +
	"\x06errors\x18\x04 \x01(\x04R\x06errors2I\n" +
	"\rMobileCapture\x128\n" +
	"\x04Push\x12\x16.gta.mobile.AgentEvent\x1a\x16.gta.mobile.PushResult(\x01B\x1eZ\x1cgta/pkg/capture/mobile/protob\x06proto3"

var (
	file_pkg_capture_mobile_proto_mobile_proto_rawDescOnce sync.Once
	file_pkg_capture_mobile_proto_mobile_proto_rawDescData []byte
)

func file_pkg_capture_mobile_proto_mobile_proto_rawDescGZIP() []byte {
	file_pkg_capture_mobile_proto_mobile_proto_rawDescOnce.Do(func() {
		file_pkg_capture_mobile_proto_mobile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_capture_mobile_proto_mobile_proto_rawDesc), len(file_pkg_capture_mobile_proto_mobile_proto_rawDesc)))
	})
	return file_pkg_capture_mobile_proto_mobile_proto_rawDescData
}

var file_pkg_capture_mobile_proto_mobile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_capture_mobile_proto_mobile_proto_goTypes = []any{
	(*AgentEvent)(nil), // 0: gta.mobile.AgentEvent
	(*ConnOpen)(nil),   // 1: gta.mobile.ConnOpen
	(*ConnData)(nil),   // 2: gta.mobile.ConnData
	(*ConnClose)(nil),  // 3: gta.mobile.ConnClose
	(*PushResult)(nil), // 4: gta.mobile.PushResult
}
var file_pkg_capture_mobile_proto_mobile_proto_depIdxs = []int32{
	1, // 0: gta.mobile.AgentEvent.open:type_name -> gta.mobile.ConnOpen
	2, // 1: gta.mobile.AgentEvent.data:type_name -> gta.mobile.ConnData
	3, // 2: gta.mobile.AgentEvent.close:type_name -> gta.mobile.ConnClose
	0, // 3: gta.mobile.MobileCapture.Push:input_type -> gta.mobile.AgentEvent
	4, // 4: gta.mobile.MobileCapture.Push:output_type -> gta.mobile.PushResult
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_capture_mobile_proto_mobile_proto_init() }
func file_pkg_capture_mobile_proto_mobile_proto_init() {
	if File_pkg_capture_mobile_proto_mobile_proto != nil {
		return
	}
	file_pkg_capture_mobile_proto_mobile_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEvent_Open)(nil),
		(*AgentEvent_Data)(nil),
		(*AgentEvent_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_capture_mobile_proto_mobile_proto_rawDesc), len(file_pkg_capture_mobile_proto_mobile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_capture_mobile_proto_mobile_proto_goTypes,
		DependencyIndexes: file_pkg_capture_mobile_proto_mobile_proto_depIdxs,
		MessageInfos:      file_pkg_capture_mobile_proto_mobile_proto_msgTypes,
	}.Build()
	File_pkg_capture_mobile_proto_mobile_proto = out.File
	file_pkg_capture_mobile_proto_mobile_proto_goTypes = nil
	file_pkg_capture_mobile_proto_mobile_proto_depIdxs = nil
}
